### ISSUE TITLE
Stuck on setup 

### ISSUE THREAD

**Issue by Mikescotland** [AlexandrErohin/home-assistant-tplink-router#1]
Tried but getting "starting configuration wizard for tp link router" and spinning wheel forever.

**Comment by AlexandrErohin** [comment]
@Mikescotland Hi
Did you restart Home Assistant? It stucks before you type host and password?
Could you tell please also
1) What is the version of your Home Assistant
2) The router version and build version. It could be found in the bottom of the router web page when you are logged
3) Is there any related logs in Home Assistant. Check please in Home Assistant Settings->System->Logs

**Comment by Mikescotland** [comment]
Yes. I restarted of course.
HA core 2023.11.2

Succesfully added via HASS.
Whenever I try to add via devices and services, immediately after choosing package it goes forever to "starting configuration wizard for tp link router" and never goes to inputting the router IP.
After a few minutes it shows message "config flow could not be loaded, unknown error"

**Comment by AlexandrErohin** [comment]
@Mikescotland Is there any errors in Settings->System->Logs ?

**Comment by Mikescotland** [comment]
All good now with the installation, redownloaded and reinstalled.
Although my tplink router is supported by TPLINK tether app (similar to yours), I think it gives different response:

0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('http://192.168.1.1/cgi-bin/luci/;stok=/login?form=keys&operation=read')

I've got Archer VR400 router.

**Comment by AlexandrErohin** [comment]
@Mikescotland yes, it looks like Archer VR400 and Archer C6U have different responses

**Comment by AlexandrErohin** [comment]
@Mikescotland  Archer MR200 v5.3 support was added, It has different api, so maybe it is similar with yours. Could you try new version of the integration and let me know
