### ISSUE TITLE
Failure adding Archer AX3000/AX55 V1.0

### ISSUE THREAD

**Issue by dkv** [AlexandrErohin/home-assistant-tplink-router#109]
**Describe the bug**
Trying to add my router fails. Using https, de-selected "verify ssl"

**Logs**
Logger: custom_components.tplink_router.config_flow
Source: /usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py:206
integration: TP-Link Router (documentation, issues)
First occurred: 11:31:02 (1 occurrences)
Last logged: 11:31:02

TplinkRouter - TPLinkDecoClient - Unknown error for pwd! Error - 'result'; Response - {"success":true,"data":{"password":["<long string, censored, looks like a hash>","010001"],"mode":"ap","username":""}}
Add also all relevant logs from **Settings->System->Logs**.

**Additional Information (please complete the following information)**
 - Router Hardware Version: V1.0
 - Router Firmware Version: 1.3.3 Build 20240628 rel.37017(4555)
 - Home Assistant Version: 2024.10.4
 - TP-Link Router Integration Component Version: v2.0.0

**Comment by AlexandrErohin** [comment]
This error in logs is ok. https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/56
Do you have any errors when adding your router via HomeAssistant UI?

**Comment by AlexandrErohin** [comment]
Could you try to install version v1.19.0 ?
Do you use your local router password? Or you use Tp-Link ID to login to the router?

**Comment by AlexandrErohin** [comment]
@dkv Could you try to delete tplink entity from HA. Then install v2.0.0. Reboot HA and add tplink with local password without encryption?
Restart HA helped here https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/111

**Comment by AlexandrErohin** [comment]
@dkv 
So, You have installer v2.0.0 of this integration and it works for your router ?

**Comment by AlexandrErohin** [comment]
@dkv Please try v2.0.1
