### ISSUE TITLE
Working, but log file errors with Archer C2300 v2.0

### ISSUE THREAD

**Issue by ColinRobbins** [AlexandrErohin/home-assistant-tplink-router#110]
**Describe the bug**
Unexpected error messages in the log files during startup of Home Assistant.

**Logs**
First I see the following
```
This error originated from a custom integration.

Logger: custom_components.tplink_router
Source: /usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py:206
integration: TP-Link Router (documentation, issues)
First occurred: 14:57:52 (1 occurrences)
Last logged: 14:57:52

TplinkRouter - TPLinkDecoClient - Unknown error for pwd! Error - 'result'; Response - {"success":true,"data":{"password":["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","010001"],"mode":"router","username":""}}
```
However the integration appears to successfully login.

Then the following appears...
```
This error originated from a custom integration.

Logger: custom_components.tplink_router
Source: custom_components/tplink_router/__init__.py:43
integration: TP-Link Router (documentation, issues)
First occurred: 14:57:56 (1 occurrences)
Last logged: 14:57:56

TplinkRouter - TplinkRouter - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/smart_network?form=game_accelerator - Response mrYHjBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxrcq8Zk=
```
Again it all seems to work, but clearly something is not right.

**Additional Information (please complete the following information)**
- Router Hardware Version: Archer C2300 v2.0
- Router Firmware Version: 1.1.4 Build 20240529 rel.41435(4555)
- Home Assistant Version: 2024.10.0
- TP-Link Router Integration Component Version: 2.0.0

**Comment by ColinRobbins** [comment]
Happy to try any recommended debugging steps, either in HA or via the python library tests.

**Comment by AlexandrErohin** [comment]
Hi
This error in logs is ok. https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/56

**Comment by ColinRobbins** [comment]
Thanks for the confirmation it is harmless.

Personally I don't like these "harmless" log file entries, so have added the following to my config.
Reporting here, incase of use to others.

```
logger:
  filters:
    custom_components.tplink_router:
      - "TplinkRouter - TPLinkDecoClient - Unknown error for pwd"
      - "TplinkRouter - TplinkRouter - An unknown response - Expecting value: line 1 column 1 (char 0)"
```

**Comment by AlexandrErohin** [comment]
@ColinRobbins These logs were hidden in v2.0.1
