### ISSUE TITLE
Error when integrating AX3000 into HA

### ISSUE THREAD

**Issue by browi2618** [AlexandrErohin/home-assistant-tplink-router#111]
can be deleted. its working again

**Comment by browi2618** [comment]
of course i reinstalled it too - same error...

**Comment by AlexandrErohin** [comment]
Would be great if you could give a star to the repo :) Thanks

**Comment by AlexandrErohin** [comment]
@browi2618 What was the problem?

**Comment by AlexandrErohin** [comment]
As there is an another member facing this problem https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/109

**Comment by browi2618** [comment]
> Would be great if you could give a star to the repo :) Thanks

i did :)
