### ISSUE TITLE
HX510 not supporting

### ISSUE THREAD

**Issue by KreeQ76** [AlexandrErohin/home-assistant-tplink-router#112]
can you please add this model HX510

**Comment by AlexandrErohin** [comment]
As I dont have this extender - Would be great if you could add support for your router by creating PR with new class that extends https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L19

**Comment by krlosrenan** [comment]
@KreeQ76, can you test with version v2.1.0 or higher? I found a mention of this model in the firmware files when I was developing compatibility with the EX511. Can you give us some feedback?

**Comment by KreeQ76** [comment]
Hi sorry for late.|
Yes I just update to version 2.1.0 and it works great.

Thanks for help.

**Comment by KreeQ76** [comment]
￼￼


I have a ittley question maby  you will have a minute to tell me how to do integration with a ME201WZ,
I already have a Z2M and device is still unsupported I find a article about this issue 
https://github.com/Koenkk/zigbee2mqtt/issues/21015￼
[New device support]: TS0601 _TZE200_lvkk0hdg (EPTTECH Tank Level Monitor Zigbee) · Issue #21015 · Koenkk/zigbee2mqtt
github.com
￼

**Comment by AlexandrErohin** [comment]
@KreeQ76 Unfortunately, I dont work with Z2M.
Could you tell what is your you hardware version for HX510 ?

**Comment by KreeQ76** [comment]
W dniu pt., 22 lis 2024 o 21:54 AlexandrErohin ***@***.***>
napisał(a):

**Comment by AlexandrErohin** [comment]
@KreeQ76 Thank you for the info!
P.S. Would be great if you could give a star to the repo :) Thanks

**Comment by KreeQ76** [comment]
Yea
Sure thanks bdw

W dniu sob., 23 lis 2024 o 14:49 AlexandrErohin ***@***.***>
napisał(a):
