### ISSUE TITLE
v2.0.0 breaks integration with Archer AC5400X

### ISSUE THREAD

**Issue by joluas** [AlexandrErohin/home-assistant-tplink-router#113]
**Describe the bug**
When updating from v1.19.0 to v2.0.0 the integration with Archer AC5400X no longer works. 

- Before update:
![image](https://github.com/user-attachments/assets/d4b014a4-147f-4ba3-8dd5-655cca8b07c8)
![image](https://github.com/user-attachments/assets/f96d4036-f425-4ed8-b42f-895abb89e1ab)

- After update:
![image](https://github.com/user-attachments/assets/ed8d31e5-5dc9-42a1-a455-1ac99add8e15)
- Encrypted password:
![image](https://github.com/user-attachments/assets/4a5b0c51-51f1-435f-b2a2-6b115b08404e)
![image](https://github.com/user-attachments/assets/503714ef-8b9b-4712-838d-324ddd24b85b)
![image](https://github.com/user-attachments/assets/5d6de9f0-8b79-4759-9856-051e024b1df6)
![image](https://github.com/user-attachments/assets/58e6a828-fd87-4984-8ff0-4a11ce2b96c1)

Even when considering https://github.com/AlexandrErohin/home-assistant-tplink-router/releases/tag/v2.0.0 and changing from encrypted password to plain text password the issue persist.
- Non encrypted password:
![image](https://github.com/user-attachments/assets/650983ef-eb92-4eb6-9c70-f7e504e0a53f)
![image](https://github.com/user-attachments/assets/c4159eff-c886-4b74-8030-1c630ac8b0a6)
![image](https://github.com/user-attachments/assets/3d0dd99b-151f-47f1-8d76-c04fabd86115)
![image](https://github.com/user-attachments/assets/651fecc0-05ad-4c93-8443-86e557bc95be)

**Reverting back to v1.19.0 solves the issues.**

**Logs**
This error originated from a custom integration.

Logger: custom_components.tplink_router.config_flow
Source: custom_components/tplink_router/config_flow.py:78
integration: TP-Link Router (documentation, issues)
First occurred: 6:27:28 PM (8 occurrences)
Last logged: 6:31:15 PM

TplinkRouter Integration Exception - TplinkRouter - C1200 - TplinkC1200Router - Cannot authorize! Error - 'stok'; Response - {'errorcode': 'login failed', 'success': False, 'data': {'failureCount': 2, 'attemptsAllowed': 8}}
TplinkRouter Integration Exception - TplinkRouter - C1200 - TplinkC1200Router - Cannot authorize! Error - 'stok'; Response - {'errorcode': 'login failed', 'success': False, 'data': {'failureCount': 3, 'attemptsAllowed': 7}}
TplinkRouter Integration Exception - HTTPSConnectionPool(host='192.168.0.1', port=443): Max retries exceeded with url: /cgi/getParm?_=1730766537416 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1000)')))
TplinkRouter Integration Exception - Your router is not supported. Please add your router support to https://github.com/AlexandrErohin/TP-Link-Archer-C6Uby implementing methods for AbstractRouter class
TplinkRouter Integration Exception - HTTPSConnectionPool(host='192.168.0.1', port=443): Max retries exceeded with url: /cgi/getParm?_=1730766675157 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1000)')))

**Additional Information (please complete the following information)**
 - Router Hardware Version: Archer AC5400X
 - Router Firmware Version: 1.1.7 Build 20240510 rel.17306(5553)
 - Home Assistant Version: 
  - Core: 2024.10.1
  - Supervisor: 2024.10.3
  - Operating system: 13.2
 - TP-Link Router Integration Component Version: v2.0.0

**Comment by AlexandrErohin** [comment]
Hi
What command did you use to get encrypted password?

**Comment by joluas** [comment]
There was a page on how to get encrypted password. The link was this -> https://github.com/AlexandrErohin/home-assistant-tplink-router#encrypted_pass The link appears to not be working any more. 

When moving from v1.19.0 to v2.0.0 I did not got a new encrypted password, I just left the same configuration that was already working in v1.19.0

**Comment by AlexandrErohin** [comment]
@joluas Could you try to delete tplink entity from HA. Then install v2.0.0. Reboot HA and add tplink with local password without encryption?

**Comment by joluas** [comment]
@AlexandrErohin I can certainly try this weekend. If you dont mind, could you please give me the steps to get the encrypted password again as I cant find them in the repo any more.

This is just in case I need to reinstall v1.19.0 again.

Thanks

**Comment by AlexandrErohin** [comment]
@joluas The bug has fixed. Please try v2.0.1 You need to use Web Encrypted Password https://github.com/AlexandrErohin/TP-Link-Archer-C6U?tab=readme-ov-file#web-encrypted-password

**Comment by joluas** [comment]
@AlexandrErohin I can confirm that it is working again using web encrypted password in v2.0.1
![image](https://github.com/user-attachments/assets/2d616d36-dc04-4b9b-98e8-e6a56ba8f449)

Thanks!
