### ISSUE TITLE
Cant setup Deco M4R(ValueError: hardware address cannot be an empty string)

### ISSUE THREAD

**Issue by ryufon** [AlexandrErohin/home-assistant-tplink-router#116]
**Describe the bug**
I cant setup deco M4R. Im using the Router IP address.

I have 2 router, one main and the other one is the extension. Im aware that i can only add the MAIN router.
When i add the main router it doesnt work, but if i add the extension it works but of course it doesnt show the connected client etc.

i thought it was a firmware update bug on the main router so i unplugged and interchange both of them, made the previous extension as main(LAN plugged) and the previous main as extension(LAN unplugged).

When i did this the behaviour is the same. now i can add the previous not working IP(now as extension) but i cant add the previous working IP(Now as main).

i always get the same error(kindly check the attached files)

I also tried deleting the entities, uninstalling, restart, reinstall then restart and add the new entry but the result is the same.

**Logs**
Add also all relevant logs from **Settings->System->Logs**.
![2024-11-12_20h39_22](https://github.com/user-attachments/assets/90743b3e-0270-4982-b3af-962322345301)
![2024-11-12_20h38_57](https://github.com/user-attachments/assets/0827b38a-0060-4995-ba62-fda5795b9d1c)
![2024-11-12_20h40_42](https://github.com/user-attachments/assets/de043842-b428-4759-b001-f25bce986e0c)

**Additional Information (please complete the following information)**
 - Router Hardware Version: M4R V2
 - Router Firmware Version: (both router) 1.6.1 Build 20231227 Rel. 80438
 - Home Assistant Version: Core: 2024.11.1/Supervisor 2024.11.2/OS 13.2/Frontend 20241106.2
 - TP-Link Router Integration Component Version: v2.0.1

**Comment by ryufon** [comment]
> Do you have the latest router firmware?

yes i do have the latest.

I think i know the reason for this. i just found out that i have one client named NON_GUEST, with no MAC address and doesnt have any ip. i think this is preventing the setup. Can you kindly give me time to investigate and put this issue on hold for a couple of hours, i will investigate and give my feedback here.

thank oyu

**Comment by AlexandrErohin** [comment]
hm, why the client has no MAC address? yes - it is the reason for this error

**Comment by ryufon** [comment]
> hm, why the client has no MAC address? yes - it is the reason for this error

Hi Alex, thank you for waiting. 

i really dont know about the cause, based on my research other users experienced this too specially when using extenders, mesh. 
one reason is that non guest is a product of a virtual client created by mesh system for internal communication between nodes. other reason i read was they call it ghost client, basically router hasnt cleared its ARP cache properly hence will still act as a CLIENT.

i fully reset both router and the mesh extension. it is solved now. 
i dont know how can i close this issue though, if you can kindly help me.

thank you again and sorry for the trouble.

**Comment by AlexandrErohin** [comment]
Thank you for your research. So if it happens sometimes - it should be supported.
I have fixed client for this behaviour - please try version 2.0.2

P.S. Would be great if you could give a star to the repo :) Thanks

**Comment by ryufon** [comment]
> Thank you for your research. So if it happens sometimes - it should be supported. I have fixed client for this behaviour - please try version 2.0.2
> 
> P.S. Would be great if you could give a star to the repo :) Thanks

Will certainly try it and i will wait for the ghost client to appear and give my feedback here. Just updated

Will do =).

**Comment by ryufon** [comment]
I restarted my router while disconnecting a couple of clients. And it happened again.

i rechecked and saw it is not working of course. due to the same error.
![2024-11-13_11h11_08](https://github.com/user-attachments/assets/25e48617-974a-49aa-b372-59a4a995226b)
![2024-11-13_11h10_54](https://github.com/user-attachments/assets/0cd5ff79-7d57-4c4d-8f06-2a5ced9665f6)

i updated to the latest version 2.0.2. And it works perfectly without any errors.
![2024-11-13_11h12_23](https://github.com/user-attachments/assets/28ed2c7f-9ae0-43cd-8767-97f20e344c12)

Thank you. i think we can close this issue.
