### ISSUE TITLE
Acheter MR550

### ISSUE THREAD

**Issue by MoiDuddits** [AlexandrErohin/home-assistant-tplink-router#118]
**Describe the bug**
Intégration ok but some entities not available
Cpu, memory, Numbers of clients

switch:
Wifi 2.4GHz => ok
Wifi 5GHz => ok
Reboot => ok

**Logs**

- Router Hardware Version: Archer MR550 v1.0 00000003
 - Router Firmware Version: 1.5.0 0.9.1 v0001.0 Build 230625 Rel.65051n
 - Home Assistant Version: 2024.11.2
 - TP-Link Router Integration Component Version: v2.0.2

**Comment by AlexandrErohin** [comment]
Hi.
Thank you for information about MR550.
As I dont have this router - would be great if you could test this client https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client/mr.py#L378 and fix the counting connected clients

P.S. Would be great if you could give a star to the repo :) Thanks
