### ISSUE TITLE
"VISIT" link address misses a colon

### ISSUE THREAD

**Issue by chunjiw** [AlexandrErohin/home-assistant-tplink-router#12]
On the "TPLinkRouter" device page, there is a "VISIT" link that if clicked, opens a browser tab with 
```
http//192.168.1.1/
```
In the address bar. Maybe you missed the colon somewhere in the code?

**Comment by AlexandrErohin** [comment]
@chunjiw Thanks!
Yes, it is a bug. It would be fixed in the next release

**Comment by AlexandrErohin** [comment]
@chunjiw fixed in v1.2.5
