### ISSUE TITLE
Extra data: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by FredFreegroup** [AlexandrErohin/home-assistant-tplink-router#13]
Hi 
When I try to add integration I receive error

Extra data: line 1 column 2 (char 1)
![chrome_Jyz04DYcz8](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/15233946/cd8e60d4-72db-4321-882c-dc9238a5e8d1)

Firmware Version:
1.13.2 Build 230824 Rel.75032n(4555)
Hardware Version:
Archer C6 4.0

Tp-Link router integration for Home Assistant
v1.2.4
@AlexandrErohin

Home Assistant Community Store
Integration version: | 1.33.0

**Comment by FredFreegroup** [comment]
reloaded and restarted twice

**Comment by FredFreegroup** [comment]
Unfortunately, I don't know where to find them :(
there is nothing in the integration folder
/homeassistant/custom_components/tplink_router/

**Comment by AlexandrErohin** [comment]
@FredFreegroup Settings -> System -> Logs

**Comment by FredFreegroup** [comment]
I didnt see logs like in massage you show :(
![chrome_wI4Jr6X9wg](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/15233946/94cb7622-9e4e-411a-b640-f0ab80206454)

**Comment by FredFreegroup** [comment]
![chrome_H15sTm8bbA](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/15233946/09b35879-88c1-4f54-9e3f-8af51ea18a27)

**Comment by AlexandrErohin** [comment]
> I didnt see logs like in massage you show :( ![chrome_wI4Jr6X9wg](https://private-user-images.githubusercontent.com/15233946/292237292-94cb7622-9e4e-411a-b640-f0ab80206454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzA3MzEsIm5iZiI6MTcwMzE3MDQzMSwicGF0aCI6Ii8xNTIzMzk0Ni8yOTIyMzcyOTItOTRjYjc2MjItOWU0ZS00MTFhLWI2NDAtZjBhYjgwMjA2NDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE0NTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYTdhMTgwOWQzYzgwYjU5NTcwYTU0ZTcwMGI4MDMyZTcyOWM2NTc1ODVmZWI5M2Q0N2MxY2Y4MzI2MjA2OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tcFbeJpR0SwH-mxJW5cqhsAOlxxIiMmyYQ4nIA-CDjg)

Press on the first log

**Comment by FredFreegroup** [comment]
found thi on search

2023-12-21 16:39:38.691 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tplink_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 16:40:51.249 ERROR (SyncWorker_1) [homeassistant.components.xiaomi.device_tracker] Invalid response: [<Response [403]>] at url: [http://192.168.31.1/cgi-bin/luci/api/xqsystem/login] with data [{'username': 'admin', 'password': '***********'}]
2023-12-21 16:47:21.406 ERROR (MainThread) [custom_components.tplink_router.config_flow] TplinkRouter Integration Exception - Extra data: line 1 column 2 (char 1)

**Comment by FredFreegroup** [comment]
![chrome_BUWUBUjj0u](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/15233946/373d627b-113b-47b2-ba02-abe4ece039f3)

**Comment by FredFreegroup** [comment]
![chrome_BUWUBUjj0u](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/15233946/29999196-2aad-4b4c-9225-bf23b63e2d11)

**Comment by AlexandrErohin** [comment]
> My router login page has no login field only password. Maybe here is the problem? ![chrome_TOAUgHPNDe](https://private-user-images.githubusercontent.com/15233946/292247969-ac32abc6-cd57-46de-90aa-3c8f384cab0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzM0NDAsIm5iZiI6MTcwMzE3MzE0MCwicGF0aCI6Ii8xNTIzMzk0Ni8yOTIyNDc5NjktYWMzMmFiYzYtY2Q1Ny00NmRlLTkwYWEtM2M4ZjM4NGNhYjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE1MzkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OTU4ODMyN2Y2MGRhMTRiZDAxYzc2ZTIxZWRiYmJiMTUzN2U1NTc5YzkwZTQwNTExODdjNzdiZjhhYjVhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rJ08EpifbEMq9WcT4YFFBlT-jU9b0WspJSDp0djoUO0)

No, Im afraid it has different encryption

Ill add more auth logs to the integration next days and we will test it

**Comment by ramonfontes** [comment]
I have the same problem with C20 and C80.

**Comment by kugaevsky** [comment]
The same issue on 
``` 
Firmware version: 1.13.2 Build 230824 Rel.75032n(5255)
Hardware version: Archer C6 4.0
```

**Comment by Flopescu** [comment]
Same issue for C80.
The login page does not ask for a user, only password, as in the screenshot above,

**Comment by AlexandrErohin** [comment]
@FredFreegroup Hi! I have added more logs for password request errors. Could you reinstall the integration, try again and post the logs?

**Comment by FredFreegroup** [comment]
Just updated

Same error with some new text:

Unknown error for pwd - Extra data: line 1 column 2 (char 1); Response - 00005

And tere is no any new records in log

**Comment by FredFreegroup** [comment]
![chrome_9dUkCkHXM9](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/15233946/7aba2a02-f4bd-4bbc-b478-f982a4947ea5)
The second line - I did not change the IP address, so ignore this error.

**Comment by AlexandrErohin** [comment]
This error means that your router has different authentication API. Since I don’t have the opportunity to test on this version of your router, you can download the client https://github.com/AlexandrErohin/TP-Link-Archer-C6U and check which requests are incorrect for authentication for this router.

**Comment by FredFreegroup** [comment]
>>> router.authorize()
Traceback (most recent call last):
  File "C:\Users\anato\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\anato\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\anato\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "y:\install\!Drivers\TP-LINK1042ND\TP-Link-Archer-C6U-1.3.1\tplinkrouterc6u\client.py", line 174, in _request_pwd
    data = response.json()
  File "C:\Users\anato\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "y:\install\!Drivers\TP-LINK1042ND\TP-Link-Archer-C6U-1.3.1\tplinkrouterc6u\client.py", line 73, in authorize
    self._request_pwd(referer)
  File "y:\install\!Drivers\TP-LINK1042ND\TP-Link-Archer-C6U-1.3.1\tplinkrouterc6u\client.py", line 183, in _request_pwd
    raise Exception('Unsupported router!')
Exception: Unsupported router!
>>>

**Comment by FredFreegroup** [comment]
It`s not suport Archer C6 4.0

**Comment by AlexandrErohin** [comment]
@FredFreegroup as I said - This error means that your router has different authentication API. You may check what requests for router authentication via browser is needed and play with the client to successed login

**Comment by FredFreegroup** [comment]
Unfortunately, I am not competent in what you wrote. I do not know how to do that. :(

**Comment by AlexandrErohin** [comment]
@FredFreegroup  Archer MR200 v5.3 support was added, It has different api, so maybe it is similar with yours. Could you try new version of the integration and let me know

**Comment by ramonfontes** [comment]
`document.getElementById("login-password").value;` doesn't work for AC750 (C20 model) and AC80.

I can successfully run `document.getElementById("pcPassword").value` on AC20 but I cannot find the ID for AC80. 

PS: You usually can find the id with the inspect ID:
![Screenshot from 2024-02-22 08-53-23](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/4843130/99636566-7458-4615-a733-d89824ce92bf)

But it doesn't work with AC80:
![Screenshot from 2024-02-22 08-53-23](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/4843130/4a4b10b9-dee0-4043-967b-d59659d41703)

Btw, `document.getElementById("pcPassword").value`  returns the clear text.

Since I don't have an encrypted password the systems now gives me the following msg error:
`You need to use web encrypted password instead. Check the documentation!`

**Comment by AlexandrErohin** [comment]
@FredFreegroup @ramonfontes @BartRuSec @kugaevsky @Flopescu Hi! Could you try the HA integration latest version please?

**Comment by AlexandrErohin** [comment]
Yes. it works only via HTTP for now
As I dont have Archer C20 would be great if you could add support for your router. Here are the examples how to do it https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/CONTRIBUTING.md
P.S. Would be great if you could give a star to the repo :) Thanks

**Comment by AnatoliiShokalo** [comment]
Hi @AlexandrErohin! I can confirm that it works on my Archer C6 v4 :) Thanks a lot!

**Comment by FredFreegroup** [comment]
Hi @AlexandrErohin! I can confirm that it works on my Archer C6 v4 :) Thanks a lot!

**Comment by AlexandrErohin** [comment]
@ramonfontes I have fixed SSL Verification - could you try the router integration via HTTPS? Only disable **Verify ssl for https connectio** in the integration configuration

**Comment by AlexandrErohin** [comment]
@ramonfontes And could you try please the integration for your Archer C20?

**Comment by ramonfontes** [comment]
@AlexandrErohin , it didn’t work, and the UI isn’t showing any errors.

**Comment by AlexandrErohin** [comment]
@ramonfontes Is there any errors in Logs?

**Comment by AlexandrErohin** [comment]
@ramonfontes And what didnt work? Archer C20 or HTTPS for C6V4?

**Comment by ramonfontes** [comment]
@AlexandrErohin,

Archer C20:

Logger: custom_components.tplink_router.config_flow
Source: custom_components/tplink_router/config_flow.py:47
integration: TP-Link Router ([documentation](https://github.com/AlexandrErohin/home-assistant-tplink-router), [issues](https://github.com/AlexandrErohin/home-assistant-tplink-router/issues))
First occurred: 7:38:22 AM (8 occurrences)
Last logged: 8:06:03 AM

TplinkRouter Integration Exception -
TplinkRouter Integration Exception - TplinkRouter - MR - Login failed. Generic error code: 71234

**Comment by AlexandrErohin** [comment]
> Hi [@AlexandrErohin](https://github.com/AlexandrErohin)! Amazing! I can confirm that it works! :) Thanks a lot!

Sorry, what router you have tested in that post?

**Comment by ramonfontes** [comment]
Archer C80: https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/13#issuecomment-1868389585

**Comment by AlexandrErohin** [comment]
@ramonfontes What is router hardware version? Could you test HTTPS with this router?

**Comment by ramonfontes** [comment]
Archer C20 v5 00000005 and  Archer C80 2.20. It doesn't work with HTTPS.

**Comment by AlexandrErohin** [comment]
@ramonfontes Is there any errors?

**Comment by ramonfontes** [comment]
@AlexandrErohin https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/13#issuecomment-2729091853

**Comment by AlexandrErohin** [comment]
@ramonfontes Have you tested HTTPS with Archer C80 2.20 with recent version of this integration?

**Comment by ramonfontes** [comment]
@AlexandrErohin, tested with V2.7.0.

**Comment by ramonfontes** [comment]
Logger: custom_components.tplink_router.config_flow
Source: custom_components/tplink_router/config_flow.py:47
integration: tplink_router ([documentation](https://github.com/AlexandrErohin/home-assistant-tplink-router), [issues](https://github.com/AlexandrErohin/home-assistant-tplink-router/issues))
First occurred: 9:27:27 AM (4 occurrences)
Last logged: 9:27:44 AM

TplinkRouter Integration Exception - HTTPSConnectionPool(host='192.168.0.1', port=443): Max retries exceeded with url: /cgi-bin/luci/;stok=/login?form=keys&operation=read (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1028)')))
TplinkRouter Integration Exception -

**Comment by AlexandrErohin** [comment]
> [@ramonfontes](https://github.com/ramonfontes) I have fixed SSL Verification - could you try the router integration via HTTPS? Only disable **Verify ssl for https connectio** in the integration configuration

@ramonfontes have you tried to disable **Verify ssl for https connectio** in the integration configuration ?

**Comment by ramonfontes** [comment]
> @ramonfontes have you tried to disable Verify ssl for https connectio in the integration configuration ?

Yes.
