### ISSUE TITLE
My TPlink router is EX510. not able to change IP, username to test,

### ISSUE THREAD

**Issue by Andersonong-github** [AlexandrErohin/home-assistant-tplink-router#15]
Hi Sir. greeting. My TP Link router is not in your list but I wonder to try out but stuck at integration. not able to change IP address from http://192.168.0.1. as my router IP is 192.168.1.254.
my router TPLink EX510.
Firmware Version: 
0.6.0 3.0.0 v6060.0 Build 230824 Rel.32637n
Hardware Version:
EX510 v1.0 00000000.

**Comment by AlexandrErohin** [comment]
@Andersonong-github For now changing IP address is available only at installation step (here https://github.com/AlexandrErohin/home-assistant-tplink-router#configuration) You have to remove the integration and configure it again

**Comment by Andersonong-github** [comment]
Thank you sir.🙏. I'll try out & update.
