### ISSUE TITLE
Can't configure integration due to "Unknown error for pwd"

### ISSUE THREAD

**Issue by oskjoh** [AlexandrErohin/home-assistant-tplink-router#17]
I'm trying to configure the integration for the first time, but after filling in router address, username, password and so on, i get the following" error message as a response and am thus unable to finnish the configuration.

> TplinkRouter Integration Exception - Unknown error for pwd - Expecting value: line 1 column 1 (char 0); Response - <body><script language="javaScript">window.parent.document.cookie="Authorization=;path=/"; window.parent.location.href = "http://192.168.0.1"; </script></body></html>

I've tried both versions 1.3.0 and 1.3.1 of your code.

I'm running Homassistant supervised on a debian 12 amd64 machine, Core: 2024.1.3, Supervisor: 2024.01.0.dev0201

![image](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/65537627/1f1e934e-5d19-45c6-8c9c-a1fa5e588f29)

**Comment by tux2000** [comment]
Same problem here, on an Archer C7 v2 (Maybe thats too old of a model for this extension?)

**Comment by AlexandrErohin** [comment]
@oskjoh What is your router?

**Comment by AlexandrErohin** [comment]
@tux2000 This integration doesnt support Archer C7 v2. It has old API that is completely different with the new API

**Comment by tux2000** [comment]
Thanks for the explanation

**Comment by oskjoh** [comment]
I also have an Archer C7 v 2.0…. realize now that it’s not supported. Sorry, my bad.
