### ISSUE TITLE
AX6000 not working

### ISSUE THREAD

**Issue by diogo-madeira** [AlexandrErohin/home-assistant-tplink-router#20]
I have a TP-link AX6000 and tried to use this integration, but it isn`t working.
I got this error:

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 15:24:05 (1 occurrences)
Last logged: 15:24:05

Error setting up entry http://192.168.0.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 34, in async_setup_entry
    username = config_entry.data[CONF_USERNAME]
               ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'username'

**Comment by AlexandrErohin** [comment]
@diogo-madeira Please, dont forget to give a star to the repo :)
