### ISSUE TITLE
Archer AX50 v1.0 seems to work OK

### ISSUE THREAD

**Issue by HACS-bank** [AlexandrErohin/home-assistant-tplink-router#21]
Archer AX50 v1.0

IoT wifi is not supported by the router but integration creates two "unavailable" entities

* switch.iot_wifi_2_4g
* switch.iot_wifi_5g

otherwise everything looks good - clients are detected, sensors are created and seem to work OK.

**Comment by AlexandrErohin** [comment]
Thank you for your router info!
Yes, sensors that are not supported by connected routers - are unavailable
