### ISSUE TITLE
Can you please add support for Tplink MR200 router 

### ISSUE THREAD

**Issue by raviteja9494** [AlexandrErohin/home-assistant-tplink-router#22]
Can you please add support for Tplink MR200 (Archer AC 750)  router , it is an LTE router. But a basic support is also good enough.
[https://www.tp-link.com/in/home-networking/3g-4g-router/archer-mr200/](https://www.tp-link.com/in/home-networking/3g-4g-router/archer-mr200/)

I am getting the below error when trying to login.
`Unknown error for pwd - Expecting value: line 1 column 1 (char 0); Response - <html><head><title>500 Internal Server Error</title></head><body><center><h1>500 Internal Server Error</h1></center></body></html>`
I can provide all the details you need.

Thanks in advance

**Comment by AlexandrErohin** [comment]
Since I don’t have the opportunity to test your router - it would be great if you could add support for your router to this client https://github.com/AlexandrErohin/TP-Link-Archer-C6U

**Comment by raviteja9494** [comment]
> As it is supported by HA basic integration, I dont think it is needed to make custom integration.

You mean the LTE integration through which we can send sms notifications?
Or am I missing any integration which is already available for my router?

**Comment by AlexandrErohin** [comment]
You said basic support is also good enough - so I decided there is integration for this.
If you want to have an integration for your router like this one - It would be great if you could add support for your router to this client https://github.com/AlexandrErohin/TP-Link-Archer-C6U

**Comment by raviteja9494** [comment]
Ok sure,
Thanks.. I'll try that and let you know if I ran into some troubles

**Comment by basettoni89** [comment]
Hi, I have the same problem (500 Internal Server Error) with my TP-Link TL-MR105.

As I'm currently on LTE connection with a fixed monthly quote I would like to integrate the modem with HA to monitor the monthly data consumption.
Is it possibile?

Thank you.

**Comment by AlexandrErohin** [comment]
@raviteja9494 @basettoni89 Please try new version - As TP-link Archer C1200 v2.0 support with different login process was added - your router may also be supported now

**Comment by oscarrdg** [comment]
Im getting the error:
`You need to use web encrypted password instead. Check the documentation!`

But when I follow the instructions trying to get the Web Encrypted Password, I'm getting this error on the web console:

`> document.getElementById("login-password").value;
VM310:1 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at <anonymous>:1:42`

**Comment by AlexandrErohin** [comment]
@oscarrdg Could you try this steps to get WebEncryptedPassword?

1. Open the browser and go to the webinterface of you TP-link router and open the developertools(ctrl+shift+i or F12).
2. In the developertools navigate to the network tab.
3. Make sure the recoder is enabeld.
4. Login to your router
5. There should appear activity in the networking tab.
6. Scroll up until you find something like  "login?form=login" and click it.
7. Click payload, and copy the string of characters, it should be a long string.
8. This is the web encrypted password.

**Comment by raviteja9494** [comment]
> Trying to configure with an TP-Link Archer RM200, I'm getting the error: `You need to use web encrypted password instead. Check the documentation!`
> 
> But when I follow the instructions trying to get the Web Encrypted Password, I'm getting this error on the web console:
> 
> `> document.getElementById("login-password").value; VM310:1 Uncaught TypeError: Cannot read properties of null (reading 'value') at <anonymos>:1:42`


Same for me also. I have tried with document.getElementById("pc-login-password").value.
I am getting my plain password. I think for mr200 it is not web encrypted.

**Comment by AlexandrErohin** [comment]
@raviteja9494 Lets try to add support for your router - https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/CONTRIBUTING.md

**Comment by raviteja9494** [comment]
> Tplink MR200 (Archer AC 750) router , it is an LTE router

Thankyou very much :)

created new issue and attached some screen shots ..

**Comment by AlexandrErohin** [comment]
@raviteja9494 @basettoni89 @oscarrdg Archer MR200 v5.3 support was added, It has different api, so maybe it is similar with yours. Could you try new version of the integration and let me know

**Comment by raviteja9494** [comment]
@AlexandrErohin  It is working for me, thankyou very much 😊

**Comment by oscarrdg** [comment]
It's still telling me to use a web encrypted password. But I'm not able to find it with the wiki instructions. 😞

I will try your suggestion on:
https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/22#issuecomment-1942218847

**Comment by AlexandrErohin** [comment]
@oscarrdg what is your hardware version?

**Comment by oscarrdg** [comment]
Hardware Version:Archer MR200 v1 00000100

**Comment by oscarrdg** [comment]
> It's still telling me to use a web encrypted password. But I'm not able to find it with the wiki instructions. 😞
> 
> I will try your suggestion on: [#22 (comment)](https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/22#issuecomment-1942218847)

I have tried that suggestion, but I haven't found anything close to "login?form=login".
What I have found is:

![Captura de pantalla 2024-02-25 194334](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/12894199/6277385e-69b6-46df-ad1f-2a20cc248e41)

And I see no payload that could be an encrypted password string, tbh. 😞

**Comment by AlexandrErohin** [comment]
@oscarrdg It looks like your router doesnt have encryption for api. But it has similar api with Archer MR200 v5. You may try to [TPLinkMRClient](https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L398C7-L398C21) without request encryption like [TplinkC1200Router](https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L367C7-L367C24) Would be great if you can add support for your router to [TP-Link-Archer-C6U](https://github.com/AlexandrErohin/TP-Link-Archer-C6U) like this [TplinkC1200Router](https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L367C7-L367C24)

**Comment by AlexandrErohin** [comment]
@oscarrdg is there any request to url like login ?

**Comment by basettoni89** [comment]
Hi! @AlexandrErohin, thanks a lot for the supporto.
With v1.9.0 I was able to add my TP-Link TL-MR105, and import all the sensors in HA.

**Comment by AlexandrErohin** [comment]
@basettoni89 What is your router hardware version?
