### ISSUE TITLE
Confirm works with  Archer AX20 v1.0

### ISSUE THREAD

**Issue by Mazoku01** [AlexandrErohin/home-assistant-tplink-router#23]
Archer AX20
by TPLink
Firmware: 1.3.8 Build 20230830 rel.19767(4555)
Hardware: Archer AX20 v1.0

![image](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/147060967/7068220d-a750-4c92-bac3-19eb2cfbdc0b)

**Comment by Mazoku01** [comment]
Well there is one problem, that this addon will disconect you from app and web.

**Comment by AlexandrErohin** [comment]
Thank you for the info about your router.
Unfortunately, the router supports only one admin login at a time, so why it disconnects from app and web
