### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by skab2** [AlexandrErohin/home-assistant-tplink-router#24]
Hi! after entering the password, this error appears.
Router ac1200 (ec220 g5)
![Screenshot_20240121-144125_Home Assistant](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/144600640/7b5cae2c-6ef2-4f5a-961e-340ef45d1a3b)

**Comment by AlexandrErohin** [comment]
Hi. It looks like your router is not supported

**Comment by milnovako** [comment]
Same thing with  "TL-MR6400(EU).

**Comment by AlexandrErohin** [comment]
As I don't have an opportunity to test your router, it would be great if you could add support for your router to this client https://github.com/AlexandrErohin/TP-Link-Archer-C6U

**Comment by nikolai2111** [comment]
Almost same here, with the TL-MR6400.

![grafik](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/10119322/910907fe-454c-40ad-84e2-5bab4de041be)

**Comment by AlexandrErohin** [comment]
@skab2 TP-link Archer C1200 v2.0 support with different login process was added

@milnovako @nikolai2111 Please try new version - As TP-link Archer C1200 v2.0 support with different login process was added - your router may also be supported now

**Comment by AlexandrErohin** [comment]
@milnovako @nikolai2111 Archer MR200 v5.3 support was added, It looks like the api is similar with yours. Could you try new version of the integration and let me know

**Comment by AlexandrErohin** [comment]
@milnovako @nikolai2111 Could you test please this integration with your TL-MR6400?

**Comment by nikolai2111** [comment]
I am sorry!

But I could not test it because it is installed in a house on the remote, which I currently have the time to go there and try the new update.

You will hear from me when I tested your new update.
