### ISSUE TITLE
Archer A7 V5

### ISSUE THREAD

**Issue by cscherpenisse** [AlexandrErohin/home-assistant-tplink-router#25]
I am trying to set up the Archer A7 V5 but it fails.
However, it appears to be connected to the Archer router because logging in via the web interface is not possible because you have already logged in.

In the HomeAssistant log I get the message below, can anyone tell me what the problem is?

Logboek Details (FOUT)
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 12:55:56 (8 occurrences)
Last logged: 13:22:27

Error setting up entry https://192.168.??.1 for tplink_router
Error setting up entry 192.168.??.1 for tplink_router
Error setting up entry http://192.168.??.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 56, in async_setup_entry
    coordinator = TPLinkRouterCoordinator(hass, device, entry.data[CONF_SCAN_INTERVAL], info, _LOGGER, entry.entry_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 22, in __init__
    self.firmware = info[0]
                    ~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by AlexandrErohin** [comment]
What is the integration version?
There was a bug with your router - but is was fixed https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/10

**Comment by AlexandrErohin** [comment]
Is there any logs like this https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/10#issuecomment-1854921431 in  Settings -> System -> Logs? any logs about custom_components.tplink_router or TplinkRouter Integration Exception ?

**Comment by cscherpenisse** [comment]
Yes the same log.
Is there a way to install and try version 1.2.3?

> Is there any logs like this [#10 (comment)](https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/10#issuecomment-1854921431) in Settings -> System -> Logs? any logs about custom_components.tplink_router or TplinkRouter Integration Exception ?

Yes the same log.
Is there a way to install and try version 1.2.3?

**Comment by AlexandrErohin** [comment]
There should be other logs also

**Comment by AlexandrErohin** [comment]
@cscherpenisse Could you try please the new version and let me know how it goes?

**Comment by cscherpenisse** [comment]
> @cscherpenisse Could you try please the new version and let me know how it goes?

You mean versie 1.10.0?
Only CPU and Memory used is not working.

**Comment by AlexandrErohin** [comment]
@cscherpenisse Yes. Thank you for testing!

**Comment by AlexandrErohin** [comment]
@cscherpenisse Hi. Could you test please v1.11.0 when you have time?
And what is your router hardware and firmware versions?
Thank you!

**Comment by cscherpenisse** [comment]
I tested it and this version works well.
Only CPU and Memory used is not working.

Firmware version: 1.2.1 Build 20220714 rel.75573(4555)
Hardware version: Archer A7 v5.0

**Comment by AlexandrErohin** [comment]
@cscherpenisse Thank you!
