### ISSUE TITLE
Confirm working with TP-Link WA-3001

### ISSUE THREAD

**Issue by JasonMeudt** [AlexandrErohin/home-assistant-tplink-router#27]
Confirm working with TP-Link WA-3001 access point as of addon v1.40.

![image](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/10866095/ba215824-bec1-4372-8aac-2ff057b5e6e1)

**Comment by AlexandrErohin** [comment]
@JasonMeudt Thank you!

**Comment by AlexandrErohin** [comment]
@JasonMeudt Please, dont forget to give a star to the repo :)
