### ISSUE TITLE
arxher ax72 v1 

### ISSUE THREAD

**Issue by MG-Sky** [AlexandrErohin/home-assistant-tplink-router#29]
**Describe the bug**

**Logs**

**Additional Information (please complete the following information)**
 - Router Hardware Version: ax 72 v1
 - Router Firmware Version: 1.2.2 Build 20230927 rel.58345(4555)
 - Home Assistant Version:  latest
 - TP-Link Router Integration Component Version: latest

integration works

btw. is there any way to add bandwidth utilisation of a router (rx and tx)

**Comment by AlexandrErohin** [comment]
Thank you for the router info!
You my also use UPnP HomeAssistant Integration that enables you to collect network statistics from your router such as bytes in/out and packets in/out, uptime, WAN IP address, and WAN connectivity status.

https://www.home-assistant.io/integrations/upnp/

**Comment by AlexandrErohin** [comment]
I have upnp installed - and it shows the real speed. By default the unit of measurement is bytes per seconds, but you may open settings for the sensor and change it to Mbit/s

**Comment by z0gst** [comment]
@MG-Sky did you have any problems setting up the integration? I am unable to set it up for the same router. Was getting an error, so tried getting a web encrypted password, but was unable to get that. Is your integration working with plain local password or with web encrypted?

**Comment by MG-Sky** [comment]
it worked in first attempt, i use plain password with IP device address

![Image](https://github.com/user-attachments/assets/f9cb4cdb-c174-4a9b-a791-c68178989609)
