### ISSUE TITLE
Tplink MR200 (Archer AC 750) router , it is an LTE router

### ISSUE THREAD

**Issue by raviteja9494** [AlexandrErohin/home-assistant-tplink-router#30]
1. logged in, the page is basic settings status tab 
2. pressed advanced settings , status tab
3. pressed advanced settings ,wireless tab , statistics
4. pressed logout
5. again logged in with password
6. pressed reboot
7. after reboot logged in again
![Advanced_settings_status_tab](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/13412480/29473c33-e148-4629-9947-0ca175e609f2)
![Advanced_settings_wireless_tab_statistics](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/13412480/48bf8328-0149-442b-b23b-e3acf64ca209)
![basic_window_after_login](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/13412480/3eda3a58-c231-460c-bb7c-5287351c63e3)

**Comment by AlexandrErohin** [comment]
You forgot to attach the captured data

**Comment by AlexandrErohin** [comment]
Unfortunately, all request are encrypted and I cannot parse them without having this router

Would be great if you could add support for your router by creating PR with new class that extends https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L16

To solve encryption I found this for your router https://github.com/0xf15h/tp_link_gdpr

**Comment by raviteja9494** [comment]
Ok I'll try that and let you know.
Thanks 😊

**Comment by AlexandrErohin** [comment]
@raviteja9494 Archer MR200 v5.3 support was added. It is also LTE router. Please new version of the integration

**Comment by raviteja9494** [comment]
@AlexandrErohin   it is working, thankyou, thankyou very much 😊

I am still going through the base to understand how to add support to my router, but you did it .. thankyou very much 😊..

I'll try to understand and if possible I'll try to add the entities for LTE signal details also .. 

Thanks 😊

**Comment by AlexandrErohin** [comment]
@raviteja9494 could you me tell please what is the hardware version of your router?

**Comment by AlexandrErohin** [comment]
@raviteja9494 Thank you!
P.S. Dont forget please to give a star to the repo :)
