### ISSUE TITLE
Router login login no longer supports Web Encrypted Password fix

### ISSUE THREAD

**Issue by tekHudson** [AlexandrErohin/home-assistant-tplink-router#31]
**Describe the bug**
While attempting to setup I received the `You need to use web encrypted password instead. Check the documentation! ` error.
I arrived at the repo and scanned the documentation finding the section describing the error and the link to the fix. I went to the fix and began to follow the steps. At my routers login I

- entered the PW
- clicked off the text field
- opened the console
- entered the command
- received and error about value of null
- investigated the element and it is not present
```html
<ul>
    <div id="login-username" class="nd">
  <li id="unLi" class="unLi"><img src="../img/login/username.png"><input class="text" id="userName" type="text" maxlength="32" placeholder="Username" autocomplete="off"></li>
  <li class="blank"></li>
    </div>
  <li id="pwLi" class="pwLi"><img src="../img/login/password.png"><input class="text" id="pcPassword" type="password" maxlength="32" placeholder="Password" autocomplete="off"></li>
</ul>
```

there appears to be a rename of the pw element.

**Logs**
Add also all relevant logs from **Settings->System->Logs**.

**Additional Information (please complete the following information)**

 - Router Hardware Version: TL-WA801N v6 00000006
 - Router Firmware Version: 0.9.1 3.16 v0001.0 Build 200116 Rel.61815n(5553)
 - Home Assistant Version: 
   - Core 2024.2.1
   - Supervisor 2024.01.1
   - Operating System 11.5
   - Frontend 20240207.1
 - TP-Link Router Integration Component Version: ??? is that this repos code? latest as of writing this ticket

**Comment by AlexandrErohin** [comment]
Could you try this command
```
document.getElementById("pcPassword").value;
```

**Comment by tekHudson** [comment]
Yeah, I was doing that, but it didn't execute the encryption against the string. It's just storing it as an input field so the value method returns simply the value attribute, which is just the password itself.

**Comment by tekHudson** [comment]
There is some JavaScript on the bottom of the page which does have some sort of AES and RSA encryption but I couldn't get it to execute against the password field but I think that's probably what would generate what you're looking for. Happy to do a pairing session or copy paste it here, if that would help.

**Comment by tekHudson** [comment]
So there isn't a simple `login?form=login` on my routers WebApp. Looks like we may have different versions. here is what i found though:

- Headers shows:
  - `http://192.168.X.XXX/cgi_gdpr` 
- Payload seems Encrypted stringish
  - sign=<anon_256_character_lowercase_alpha_numeric>
  - data=<anon_128_character_upper_and_lowercase_with_2_`+`_signs>

**Comment by LaurentCole** [comment]
Hi,
I have tp-link archer C6 V4.0, firmware 1.13.2 build 230824
I connected to the console, developpertools, network tab but can't find the login in the records.

Can you help please.
Thx
Laurent

**Comment by LaurentCole** [comment]
Hi,
Updated the integration but still not working

**Comment by AlexandrErohin** [comment]
@tekHudson Hi. Could you test please the new version of this integration with you TL-WA801N v6 ?

**Comment by LaurentCole** [comment]
Hi,
updated to 1.7.0

my TP-Link : Archer C6 v.4

I need to use encrypted password

Did the « web encrypted password » procedure

Not working
Cannot find document.getElementById("login-password").value;

**Comment by plord12** [comment]
I have the same issue with my Archer C8

**Comment by Borty97** [comment]
Me too. The password field does not have any ID associated, so this bypass does not work. Eventhough, it should return the same input:
![image](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/60492018/257ba15e-64db-4fd5-910b-989bd34c123c)

Here I added the ``login-password`` ID, and looked up for ``document.getElementById("login-password").value``:
![image](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/60492018/0c6f7de1-7ac3-4403-8945-a33e7b01bf79)

**Comment by Borty97** [comment]
I found a ``tpEncrypt.new.js?t=XXXXXXX`` file after login. One string 255 characters long found, but it isn't. Nothing seems to be there. Any ideas?

**Comment by AlexandrErohin** [comment]
@Borty97 What is your router hardware version?

**Comment by Borty97** [comment]
> @Borty97 What is your router hardware version?

Archer C6 4.0
Firmware 1.13.2 Bulld 230824 Rel. 75032n(4555)

**Comment by Arun-R-S** [comment]
Hi @AlexandrErohin, I am also facing the same issue. I cannot find the password for the below command. recieving the null value

document.getElementById("login-password").value;

My Device details below

Firmware Version:
1.13.2 Build 230824 Rel.75032n(5553)
Hardware Version:
Archer C80 2.0

**Comment by AlexandrErohin** [comment]
@Arun-R-S @Borty97 Archer C80 2.0 and Archer C6 4.0 has same API which is not supported by this integration currently. As I dont have any of these routers - I cannot add support for them

Would be great if you could add the support for this routers by implementing methods for TplinkC6V4Router class here https://github.com/AlexandrErohin/TP-Link-Archer-C6U/blob/main/tplinkrouterc6u/client.py#L644

**Comment by Arun-R-S** [comment]
@AlexandrErohin I am not sure how to add that.

@Borty97 do you have any idea on this?

**Comment by Arun-R-S** [comment]
@AlexandrErohin, can you tell me how to add that. I will try to work on this.

**Comment by AlexandrErohin** [comment]
@Arun-R-S You have to find out how the encryption works for this router in JS files. Unfortunately, there is no concrete algorithm for that

**Comment by aventouris** [comment]
Hello.

The same problem with the encrypted password here.

TP-LINK TL-WA901N
HW: WA901N v6 00000000
FW: 3.16.9 Build 220701 Rel.62854n (4555)

**Comment by programista4** [comment]
If we have already encrypted password, do we get "You need to use web encrypted password instead. Check the documentation!" message if our router is not supported or the message will be different?

**Comment by AlexandrErohin** [comment]
@programista4 What is your router hardware?

**Comment by programista4** [comment]
This is TL-WA854RE v3.0 - repeater.

**Comment by Niels7801** [comment]
Also cannot retrieve web encrypted password, get below error:

VM91:1 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at <anonymous>:1:42

Router Deco M5
FW version: 1.7.4 Build 20231222 Rel. 63684

Thanks in advance

**Comment by aventouris** [comment]
Hello. Mine is TL-WA901N

**Comment by Niels7801** [comment]
> Could you try this steps to get WebEncryptedPassword?
> 
> 1. Open the browser and go to the webinterface of you TP-link router and open the developertools(ctrl+shift+i or F12).
> 2. In the developertools navigate to the network tab.
> 3. Make sure the recoder is enabeld.
> 4. Login to your router
> 5. There should appear activity in the networking tab.
> 6. Scroll up until you find something like  "login?form=login" and click it.
> 7. Click payload, and copy the string of characters, it should be a long string.
> 8. This is the web encrypted password.

also tried above (copied the encrypted password) but get autentication error while trying to setup Home Assistant integration. (tried with http://... and https://... also checked to uncheck ssl in both situations but no luck)

**Comment by AlexandrErohin** [comment]
@Niels7801 Could you add also all relevant logs from **Settings->System->Logs**?

**Comment by akshaydogra1** [comment]
Hi,

Same Issue. Unable to get encrypted password.

Device: Archer A10
Firmware Version:1.0.5 0.9.1 v1000.0 Build 200928 Rel.32191n(5553) 
Hardware Version:Archer A10 v1

**Comment by tekHudson** [comment]
I am stopping following this thread, I moved to a Unify home setup

**Comment by AlexandrErohin** [comment]
@akshaydogra1 Hi! Could you try the latest integration release?

**Comment by AlexandrErohin** [comment]
@Niels7801 Hi! Do you still have problem with Deco M5 ?

**Comment by akshaydogra1** [comment]
@AlexandrErohin , 

Tried to follow steps mentioned for web encrypted password, still does not work:

Steps taken:
Go to the login page of your router. (default: 192.168.0.1).
Type in the password you use to login into the password field.
Click somewhere else on the page so that the password field is not selected anymore.
Open the JavaScript console of your browser (usually by pressing F12 and then clicking on "Console").
Type document.getElementById("login-password").value;
Copy the returned value as password and use it.

It throws an error on typing' document.getElementById("login-password").value' at console

Error- "Uncaught TypeError: Cannot read properties of null (reading 'value')"
