### ISSUE TITLE
6Ghz support?

### ISSUE THREAD

**Issue by Roedandan** [AlexandrErohin/home-assistant-tplink-router#33]
Hi!

Is there any way for you to add support for the 6Ghz (wifi 6E) band?

I'm using an AXE75 V1 on 1.1.9 Build 20231115

**Comment by AlexandrErohin** [comment]
Hi
Does all integration's features works for your AXE75 V1 ?

As my router doesnt support 6Ghz wifi, could you:
1) download this client https://github.com/AlexandrErohin/TP-Link-Archer-C6U
2) run
```
from tplinkrouterc6u import TplinkRouter
from logging import Logger


client = TplinkRouter('192.168.0.1', 'password', logger=Logger('test'))
print(client.request('admin/status?form=all&operation=read'))
```
3) Post here the output

**Comment by AlexandrErohin** [comment]
Added Support for Wifi 6G
