### ISSUE TITLE
How to change scan interval to an installed config?

### ISSUE THREAD

**Issue by latunnqj-shtangist** [AlexandrErohin/home-assistant-tplink-router#35]
**Describe the bug**

**Logs**
Add also all relevant logs from **Settings->System->Logs**.

**Additional Information (please complete the following information)**
 - Router Hardware Version:
 - Router Firmware Version:
 - Home Assistant Version: 
 - TP-Link Router Integration Component Version:

**Comment by AlexandrErohin** [comment]
@latunnqj-shtangist Added to configuration
