### ISSUE TITLE
Allow device_tracker to also log wired devices

### ISSUE THREAD

**Issue by sjthuss** [AlexandrErohin/home-assistant-tplink-router#38]
**Describe the bug**
I am using a TP-Link AXE5400 router as my main network device. I also have a secondary router (Archer C80) configured as an access point and connected to the main router via ethernet.

When a device is connected via wifi to the main router, device_tracker is able to log the device as being "home". However, if the device is connected via wifi to the access point router, it will appear in the device list on the main router as a "wired connection", and device_tracker is not able to detect the device, showing it as "away".

**Additional Information (please complete the following information)**
Router:
AXE5400 Tri-Band Wi-Fi 6E Router
Firmware Version:
1.1.9 Build 20231115 rel.37295(4341)
Hardware Version:
Archer AXE75 v1.0

 - Home Assistant Version: 
 - Core
2024.3.0
Frontend
20240306.0

 - TP-Link Router Integration Component Version: current version

**Comment by AlexandrErohin** [comment]
Im not sure that wired devices should be tracked as device_tracker. I think this problem can be solved if second router would be connected to HomeAssistant also. But, unfortunately, Archer C80 is not supported right now

**Comment by 3raser95** [comment]
I would also appreciate something like this since I would like to do automations whenever a wired client turns on but currently I can't do it. It could possibly just be a sensor with states `connected` and `disconnected` since a tracker is probably not necessary.

**Comment by 3raser95** [comment]
I have an Archer AX23

**Comment by AlexandrErohin** [comment]
@3raser95 Archer AX23 looks like router's name
Maybe your Hardware Version: is AX1800 V ..?

**Comment by 3raser95** [comment]
![Screenshot_20240401_124110_Tether](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/38729127/aadf55fb-ad95-444b-b5e3-a683b536b1c8)
Mine just says Archer AX23 V1.0 but on the TP-Link website it says AX23 | AX1800

**Comment by AlexandrErohin** [comment]
@sjthuss @3raser95 Added wired clients to device_tracker in the new version. Please download and let me know

**Comment by 3raser95** [comment]
Thank you! I've tested it now with my setup and everything works well. Obviously there is a delay but that's just how it is with a periodic check for changes. On my part this issue can be closed but I hope @sjthuss could confirm everything works for him too.

**Comment by sjthuss** [comment]
> @sjthuss @3raser95 Added wired clients to device_tracker in the new version. Please download and let me know

I can confirm that it is working perfectly for me as well. Thank you for the update!

**Comment by AlexandrErohin** [comment]
Dont forget please to give a star to the repo :)
