### ISSUE TITLE
MR6400 information

### ISSUE THREAD

**Issue by NotCarr** [AlexandrErohin/home-assistant-tplink-router#39]
MR6400 is partially supported. Here it is used as 4g router/modem
![tplink6400](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/98609721/18dd96fc-1478-494d-b19f-026797073a3e)
 connected to my main router.

See attached screenshot for router device page in home assistant for all tech details and entities

**Additional Information (please complete the following information)**
 - Router Hardware Version: see screenshot
 - Router Firmware Version: see screenshot
 - Home Assistant Version: 2024.3.1
 - TP-Link Router Integration Component Version: 1.10

**Comment by AlexandrErohin** [comment]
Thank you for the information!

P.S.  Dont forget please to give a star to the repo :)
