### ISSUE TITLE
Cannot Add Integration: "Config flow could not be loaded: Unknown error"

### ISSUE THREAD

**Issue by mediacutlet** [AlexandrErohin/home-assistant-tplink-router#41]
**Describe the bug**
I followed HACS installation instructions. After restarting HA, attempting to Add the integration causes the following error to display after about 30 seconds of attempting to load. It should be noted that I am using the latest firmware version which has recently added support for EasyMesh. This was a big firmware update so it is quite possibly related.

Thank you for your time and any assistance you can provide.

![image](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/26329687/2bb53f83-139b-40a2-9717-7acb0b231b5a)
 

**Logs**
The only log entries from the time period when the attempts were made is the one below which I do not think is related.

Logger: homeassistant.helpers.script.trigger_update_coordinator
Source: helpers/script.py:1805
First occurred: 8:07:00 AM (7 occurrences)
Last logged: 8:13:03 AM

Trigger Update Coordinator: Running script requires passing in a context

**Additional Information (please complete the following information)**
 - Router Hardware Version: AX5400 Wi-Fi 6 Router (Archer AX73 v1.0)
 - Router Firmware Version: 1.3.5 Build 20230922 rel.71211(5553)

 - Home Assistant Version: 2024.3.1
 - TP-Link Router Integration Component Version: v1.10.0

**Comment by AlexandrErohin** [comment]
Hi.
This log is not related to the integration

Could you try to install new version of the integration

**Comment by mediacutlet** [comment]
Upgrading to 1.11.0 did the trick. Thanks so much. This integration rocks by the way!
