### ISSUE TITLE
Add support to Archer MR600 v3

### ISSUE THREAD

**Issue by Skifou** [AlexandrErohin/home-assistant-tplink-router#43]
Hi @AlexandrErohin

I tried by opportunity your great integration with Archer MR600 v3 00000002, having seen the support of the v1 has been recently added.

**Logs**

> Enregistreur: homeassistant.config_entries
> Source: config_entries.py:504
> S'est produit pour la première fois: 07:22:05 (3 occurrences)
> Dernier enregistrement: 07:23:31
> 
> Error setting up entry http://192.168.1.1 for tplink_router
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/tplink_router/__init__.py", line 47, in async_setup_entry
>     firmware, status = await hass.async_add_executor_job(TPLinkRouterCoordinator.request, client, callback)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/tplink_router/coordinator.py", line 56, in request
>     data = callback()
>            ^^^^^^^^^^
>   File "/config/custom_components/tplink_router/__init__.py", line 43, in callback
>     stat = client.get_status()
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 756, in get_status
>     status._lan_macaddr = macaddress.EUI48(values['0']['X_TP_MACAddress'])
>                                            ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
> TypeError: list indices must be integers or slices, not str

**Additional Information (please complete the following information)**
 - Router Hardware Version: Archer MR600 v3 00000002
 - Router Firmware Version: 1.1.0 0.9.1 v0001.0 Build 220727 Rel.74013n
 - Home Assistant Version: 2024.3.3
 - TP-Link Router Integration Component Version: v1.11.3

Thanks a lot
Skifou

**Comment by AlexandrErohin** [comment]
@Skifou Hi!
As I dont have this router - could you help me to get next thing to be able to add the support for your router
1) Download please the client https://github.com/AlexandrErohin/TP-Link-Archer-C6U
2) Run this script
```
from tplinkrouterc6u import TPLinkMRClient
from logging import Logger

client = TPLinkMRClient('192.168.0.1', 'your_password', logger=Logger('test'))
client.authorize()

acts = [
    TPLinkMRClient.ActItem(TPLinkMRClient.ActItem.GS, 'LAN_IP_INTF', attrs=['X_TP_MACAddress', 'IPInterfaceIPAddress']),
    TPLinkMRClient.ActItem(TPLinkMRClient.ActItem.GS, 'WAN_IP_CONN',
                           attrs=['enable', 'MACAddress', 'externalIPAddress', 'defaultGateway']),
    TPLinkMRClient.ActItem(TPLinkMRClient.ActItem.GL, 'LAN_WLAN', attrs=['enable', 'X_TP_Band']),
    TPLinkMRClient.ActItem(TPLinkMRClient.ActItem.GL, 'LAN_WLAN_GUESTNET', attrs=['enable', 'name']),
    TPLinkMRClient.ActItem(TPLinkMRClient.ActItem.GL, 'LAN_HOST_ENTRY', attrs=[
        'IPAddress',
        'MACAddress',
        'hostName',
        'X_TP_ConnType',
        'active',
    ]),
    TPLinkMRClient.ActItem(TPLinkMRClient.ActItem.GS, 'LAN_WLAN_ASSOC_DEV', attrs=[
        'associatedDeviceMACAddress',
        'X_TP_TotalPacketsSent',
        'X_TP_TotalPacketsReceived',
    ]),
]
result, values = client.req_act(acts)
print(result)
print(values)
```
4) Post here the output

**Comment by Skifou** [comment]
Thanks a lot for the so-fast answer.
Maybe a question of newbe, I'm not so specialist in running python script, sorry for that, but where shall I run this script ?
On my homeassistant server (my first guess) ? or can I run it from any Windows PC connected to the LAN ?
Thanks again for your advise

**Comment by AlexandrErohin** [comment]
You may run it on your Windows PC connected to the LAN

**Comment by Skifou** [comment]
Thanks, I will manage asap and post it back here.

**Comment by AlexandrErohin** [comment]
@Skifou Is there any news?

**Comment by Skifou** [comment]
Sorry @AlexandrErohin , I'm on business trip until tomorrow. I can't access my network for now.
You will get the result of the script by this week-end :-)

**Comment by Skifou** [comment]
Hi @AlexandrErohin 
Here is the result:
`[1,1,0,0,0,0]0
X_TP_MACAddress=48:22:54:0F:87:4B
IPInterfaceIPAddress=192.168.1.1
[1,2,0,0,0,0]0
X_TP_MACAddress=48:22:54:0F:87:4B
IPInterfaceIPAddress=192.168.0.110
[1,1,1,0,0,0]1
enable=0
MACAddress=
externalIPAddress=0.0.0.0
defaultGateway=0.0.0.0
[2,1,1,0,0,0]1
enable=1
MACAddress=48:22:54:0F:87:4C
externalIPAddress=10.111.110.247
defaultGateway=10.111.110.248
[1,1,0,0,0,0]2
enable=1
X_TP_Band=2.4GHz
[1,2,0,0,0,0]2
enable=1
X_TP_Band=5GHz
[1,1,0,0,0,0]3
enable=1
name=wlan1
[1,2,0,0,0,0]3
enable=1
name=wlan6
[1,0,0,0,0,0]4
IPAddress=192.168.1.25
MACAddress=98:CD:AC:1F:B5:4B
hostName=Shelly Chambre Bleue
X_TP_ConnType=1
active=1
[2,0,0,0,0,0]4
IPAddress=192.168.1.31
MACAddress=3C:E9:0E:C7:E6:CA
hostName=Shelly Prise Refrigerateur
X_TP_ConnType=1
active=1
[3,0,0,0,0,0]4
IPAddress=192.168.1.51
MACAddress=34:94:54:6B:31:BD
hostName=Shelly Ampoule Salon
X_TP_ConnType=1
active=1
[4,0,0,0,0,0]4
IPAddress=192.168.1.26
MACAddress=98:CD:AC:1E:35:74
hostName=Shelly Chambre Mezzanine
X_TP_ConnType=1
active=1
[5,0,0,0,0,0]4
IPAddress=192.168.1.13
MACAddress=C8:12:0B:37:64:F2
hostName=Samsung TV
X_TP_ConnType=3
active=1
[6,0,0,0,0,0]4
IPAddress=192.168.1.12
MACAddress=F0:08:D1:5B:C8:A0
hostName=Climatisation Salon
X_TP_ConnType=1
active=1
[7,0,0,0,0,0]4
IPAddress=192.168.1.10
MACAddress=28:11:A8:A5:8C:9B
hostName=homeassistantcanet
X_TP_ConnType=3
active=1
[8,0,0,0,0,0]4
IPAddress=192.168.1.23
MACAddress=E8:DB:84:D6:70:82
hostName=Shelly Switch Entree
X_TP_ConnType=1
active=1
[9,0,0,0,0,0]4
IPAddress=192.168.1.21
MACAddress=B8:D6:1A:86:E5:54
hostName=Shelly Plus Chauffe Eau
X_TP_ConnType=1
active=1
[10,0,0,0,0,0]4
IPAddress=192.168.1.11
MACAddress=70:3A:2D:56:2A:D2
hostName=Camera IP
X_TP_ConnType=1
active=1
[11,0,0,0,0,0]4
IPAddress=192.168.1.14
MACAddress=A2:A6:5A:09:7A:4F
hostName=Galaxy-Sebastien-VOEGELE
X_TP_ConnType=3
active=1
[12,0,0,0,0,0]4
IPAddress=192.168.1.15
MACAddress=02:72:63:2C:86:7E
hostName=Galaxy-Tab-S5e
X_TP_ConnType=3
active=1
[13,0,0,0,0,0]4
IPAddress=192.168.1.16
MACAddress=C8:F7:33:D9:03:B6
hostName=PC-FAMILLE
X_TP_ConnType=3
active=1
[1,1,1,0,0,0]5
associatedDeviceMACAddress=F0:08:D1:5B:C8:A0
X_TP_TotalPacketsSent=247
X_TP_TotalPacketsReceived=519
[1,1,2,0,0,0]5
associatedDeviceMACAddress=34:94:54:6B:31:BD
X_TP_TotalPacketsSent=407
X_TP_TotalPacketsReceived=1044
[1,1,3,0,0,0]5
associatedDeviceMACAddress=70:3A:2D:56:2A:D2
X_TP_TotalPacketsSent=4696317
X_TP_TotalPacketsReceived=5181144
[1,1,4,0,0,0]5
associatedDeviceMACAddress=E8:DB:84:D6:70:82
X_TP_TotalPacketsSent=57
X_TP_TotalPacketsReceived=8293
[1,1,5,0,0,0]5
associatedDeviceMACAddress=98:CD:AC:1F:B5:4B
X_TP_TotalPacketsSent=56
X_TP_TotalPacketsReceived=8441
[1,1,6,0,0,0]5
associatedDeviceMACAddress=98:CD:AC:1E:35:74
X_TP_TotalPacketsSent=59
X_TP_TotalPacketsReceived=8359
[1,1,7,0,0,0]5
associatedDeviceMACAddress=3C:E9:0E:C7:E6:CA
X_TP_TotalPacketsSent=97
X_TP_TotalPacketsReceived=8340
[1,1,8,0,0,0]5
associatedDeviceMACAddress=B8:D6:1A:86:E5:54
X_TP_TotalPacketsSent=6998
X_TP_TotalPacketsReceived=8066
[1,2,1,0,0,0]5
associatedDeviceMACAddress=C8:12:0B:37:64:F2
X_TP_TotalPacketsSent=244666
X_TP_TotalPacketsReceived=97810
[1,2,2,0,0,0]5
associatedDeviceMACAddress=28:11:A8:A5:8C:9B
X_TP_TotalPacketsSent=22458
X_TP_TotalPacketsReceived=18173
[1,2,3,0,0,0]5
associatedDeviceMACAddress=A2:A6:5A:09:7A:4F
X_TP_TotalPacketsSent=148048
X_TP_TotalPacketsReceived=30069
[1,2,4,0,0,0]5
associatedDeviceMACAddress=02:72:63:2C:86:7E
X_TP_TotalPacketsSent=5
X_TP_TotalPacketsReceived=35
[1,2,5,0,0,0]5
associatedDeviceMACAddress=C8:F7:33:D9:03:B6
X_TP_TotalPacketsSent=11799
X_TP_TotalPacketsReceived=6364
[error]0

{'0': [{'X_TP_MACAddress': '48:22:54:0F:87:4B', 'IPInterfaceIPAddress': '192.168.1.1'}, {'X_TP_MACAddress': '48:22:54:0F:87:4B', 'IPInterfaceIPAddress': '192.168.0.110'}], '1': [{'enable': '0', 'MACAddress': '', 'externalIPAddress': '0.0.0.0', 'defaultGateway': '0.0.0.0'}, {'enable': '1', 'MACAddress': '48:22:54:0F:87:4C', 'externalIPAddress': '10.111.110.247', 'defaultGateway': '10.111.110.248'}], '2': [{'enable': '1', 'X_TP_Band': '2.4GHz'}, {'enable': '1', 'X_TP_Band': '5GHz'}], '3': [{'enable': '1', 'name': 'wlan1'}, {'enable': '1', 'name': 'wlan6'}], '4': [{'IPAddress': '192.168.1.25', 'MACAddress': '98:CD:AC:1F:B5:4B', 'hostName': 'Shelly Chambre Bleue', 'X_TP_ConnType': '1', 'active': '1'}, {'IPAddress': '192.168.1.31', 'MACAddress': '3C:E9:0E:C7:E6:CA', 'hostName': 'Shelly Prise Refrigerateur', 'X_TP_ConnType': '1', 'active': '1'}, {'IPAddress': '192.168.1.51', 'MACAddress': '34:94:54:6B:31:BD', 'hostName': 'Shelly Ampoule Salon', 'X_TP_ConnType': '1', 'active': '1'}, {'IPAddress': '192.168.1.26', 'MACAddress': '98:CD:AC:1E:35:74', 'hostName': 'Shelly Chambre Mezzanine', 'X_TP_ConnType': '1', 'active': '1'}, {'IPAddress': '192.168.1.13', 'MACAddress': 'C8:12:0B:37:64:F2', 'hostName': 'Samsung TV', 'X_TP_ConnType': '3', 'active': '1'}, {'IPAddress': '192.168.1.12', 'MACAddress': 'F0:08:D1:5B:C8:A0', 'hostName': 'Climatisation Salon', 'X_TP_ConnType': '1', 'active': '1'}, {'IPAddress': '192.168.1.10', 'MACAddress': '28:11:A8:A5:8C:9B', 'hostName': 'homeassistantcanet', 'X_TP_ConnType': '3', 'active': '1'}, {'IPAddress': '192.168.1.23', 'MACAddress': 'E8:DB:84:D6:70:82', 'hostName': 'Shelly Switch Entree', 'X_TP_ConnType': '1', 'active': '1'}, {'IPAddress': '192.168.1.16', 'MACAddress': 'C8:F7:33:D9:03:B6', 'hostName': 'PC-FAMILLE', 'X_TP_ConnType': '3', 'active': '1'}], '5': [{'associatedDeviceMACAddress': 'F0:08:D1:5B:C8:A0', 'X_TP_TotalPacketsSent': '247', 'X_TP_TotalPacketsReceived': '519'}, {'associatedDeviceMACAddress': '34:94:54:6B:31:BD', 'X_TP_TotalPacketsSent': '407', 'X_TP_TotalPacketsReceived': '1044'}, {'associatedDeviceMACAddress': '70:3A:2D:56:2A:D2', 'X_TP_TotalPacketsSent': '4696317', 'X_TP_TotalPacketsReceived': '5181144'}, {'associatedDeviceMACAddress': 'E8:DB:84:D6:70:82', 'X_TP_TotalPacketsSent': '57', 'X_TP_TotalPacketsReceived': '8293'}, {'associatedDeviceMACAddress': '98:CD:AC:1F:B5:4B', 'X_TP_TotalPacketsSent': '56', 'X_TP_TotalPacketsReceived': '8441'}, {'associatedDeviceMACAddress': '98:CD:AC:1E:35:74', 'X_TP_TotalPacketsSent': '59', 'X_TP_TotalPacketsReceived': '8359'}, {'associatedDeviceMACAddress': '3C:E9:0E:C7:E6:CA', 'X_TP_TotalPacketsSent': '97', 'X_TP_TotalPacketsReceived': '8340'}, {'associatedDeviceMACAddress': 'B8:D6:1A:86:E5:54', 'X_TP_TotalPacketsSent': '6998', 'X_TP_TotalPacketsReceived': '8066'}, {'associatedDeviceMACAddress': 'C8:12:0B:37:64:F2', 'X_TP_TotalPacketsSent': '244666', 'X_TP_TotalPacketsReceived': '97810'}, {'associatedDeviceMACAddress': '28:11:A8:A5:8C:9B', 'X_TP_TotalPacketsSent': '22458', 'X_TP_TotalPacketsReceived': '18173'}, {'associatedDeviceMACAddress': 'A2:A6:5A:09:7A:4F', 'X_TP_TotalPacketsSent': '148048', 'X_TP_TotalPacketsReceived': '30069'}, {'associatedDeviceMACAddress': '02:72:63:2C:86:7E', 'X_TP_TotalPacketsSent': '5', 'X_TP_TotalPacketsReceived': '35'}, {'associatedDeviceMACAddress': 'C8:F7:33:D9:03:B6', 'X_TP_TotalPacketsSent': '11799', 'X_TP_TotalPacketsReceived': '6364'}]}`

**Comment by AlexandrErohin** [comment]
@Skifou Thank you! Ill fix the client in next few days

**Comment by Skifou** [comment]
Many thanks ! looking forward to test it!

**Comment by AlexandrErohin** [comment]
@Skifou Added your router support

**Comment by Skifou** [comment]
So thankfull to such a quick reaction !! Milles merci !!
I will test and keep you posted if I find something.

**Comment by AlexandrErohin** [comment]
@Skifou Dont forget please to give a star to the repo :)
