### ISSUE TITLE
tested with AX1500 

### ISSUE THREAD

**Issue by devilio** [AlexandrErohin/home-assistant-tplink-router#44]
My router data:
Name: AX1500 Gigabit Wi-Fi 6 Router
Firmware: 1.0.20 Build 20230616 Rel. 40941(4555)
Hardver: Archer AX12 v1.0

The integratinon working, without SSL :)

**Comment by AlexandrErohin** [comment]
Thank you for the info!

P.S. Dont forget please to give a star to the repo :)

**Comment by devilio** [comment]
If you need to log in to the router for some reason, you have to temporarily disable the integration because it keeps popping out of the router...

**Comment by AlexandrErohin** [comment]
@devilio Yes
Unfortunately, TP-Link Web Interface only supports upto 1 user logged in at a time (for security reasons, apparently).
