### ISSUE TITLE
Add Deco M9 pro to router list (with a disclaimer)

### ISSUE THREAD

**Issue by Verguldebarman** [AlexandrErohin/home-assistant-tplink-router#47]
I have just tested my Deco M9 pro and the integration can find them. 

**All the sensors work, example:**

CPU used				8,0%
Memory used			37,0%
Total clients			26
Total guest wifi clients	0
Total IoT clients		Unavailable
Total main wifi clients	22
Total wired clients		4

The switches however do not work, except for [Reboot]. The switches in the integration show an on/off button. Also they show the correct state, but when pressed the following error is displayed:

`Failed to call service switch/turn_off. HTTPConnectionPool(host='192.168.0.251', port=80): Max retries exceeded with url: /cgi-bin/luci/;stok=/login?form=login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f090646cfe0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))`

That can be easily explained because the Deco M9 pro local website doesn't have the option to turn WIFI on/off.  
So no action is needed for troubleshooting.

I only ask to add Deco M9 pro to router list (with above disclaimer).

**Comment by Verguldebarman** [comment]
⭐ Starred !

I have two types in my house:

Model		Firmware Version
M9Plus(2.2)	1.6.3 Build 20231225 Rel. 60770
M4R(2.0)		1.6.1 Build 20231227 Rel. 80438

**Comment by AlexandrErohin** [comment]
@Verguldebarman Thank you!

Could you test this integration with M4R(2.0) to turn on/off wifi?

**Comment by Verguldebarman** [comment]
M4R(2.0) turn on/off wifi works. No errors in HA. I cannot test if the WiFi is actually turned on/off on the device as I don't know how to test or check it. Any suggestions?

**Comment by AlexandrErohin** [comment]
@Verguldebarman To check if the WiFi is actually turned on/off you may use Deco App on your phone. After turning off the wifi via integration you may check the wifi status in the app.
