### ISSUE TITLE
Archer AX55 (AX3000 v1.2) error

### ISSUE THREAD

**Issue by NeoFax75** [AlexandrErohin/home-assistant-tplink-router#5]
It did not work on my AX300 v1.2:

Firmware Version:
1.2.5 Build 20231025 rel.50143(5553)
Hardware Version:
Archer AX55 v1.0

`Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 6:23:52 PM (2 occurrences)
Last logged: 6:37:28 PM

Error setting up entry 192.168.0.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 36, in async_setup_entry
    coord = TPLinkRouterCoordinator(hass, device, config_entry.data[CONF_SCAN_INTERVAL], info, _LOGGER)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 19, in __init__
    self.firmware = info[0]
                    ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
`

**Comment by AlexandrErohin** [comment]
@NeoFax75 Thanks for the info!
Yes, Hardware Version - Archer AX55 v1.0 is not supported as it has different API

Hardware Version - AX3000 v1.0 should be supported.

Thanks to your info - Hardware Version - AX3000 newer then v1.0 is not supported. Ill update the supported list

**Comment by AlexandrErohin** [comment]
@NeoFax75 Archer C7 v5.0 support was added. It looks like your router has same api. Please reinstall and check again

**Comment by NeoFax75** [comment]
> @NeoFax75 Archer C7 v5.0 support was added. It looks like your router has same api. Please reinstall and check again

Yes, it works.  Checked it out yesterday and had a hard time upgrading from 0.9(?) to 1.2.4, but once it did, it worked automatically.  Thanks!
