### ISSUE TITLE
ERROR : TplinkRouter - TPLinkDecoClient - Unknown error for pwd! 

### ISSUE THREAD

**Issue by Paul1865** [AlexandrErohin/home-assistant-tplink-router#56]
**Describe the bug**
I have this error a few weeks by now. It doesn't seem to affect the sensor very much I think. Reason I am reporting this now, is that the error doesn't go away.

**Error**
Logger: custom_components.tplink_router
Source: /usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py:204
integration: TP-Link Router (documentation, issues)
First occurred: 19:18:16 (1 occurrences)
Last logged: 19:18:16
TplinkRouter - TPLinkDecoClient - Unknown error for pwd! Error - 'result'; Response - {"success":true,"data":{"password":["D...etc...BFD","010001"],"mode":"ap","username":""}}.

I checked the password via developer tools as suggested in an earlier issue. It's the same (D1E79F...etc...BFD)

**Additional Information (please complete the following information)**
 - Archer AX11000 v1.0
 - Firmware versie: 1.3.4 Build 20230906 rel.74809(4555)
 - Home Assistant Version: core-2024.5.1
 - TP-Link Router Integration Component Version: 1.13.2

**Comment by AlexandrErohin** [comment]
Hi! This error is ok. As there are different router's API the integrations try to connect to router by different ways. And when it gets fail it write a log.

Ill try to disable this log

**Comment by TheRealFalseReality** [comment]
I have this same error but the device is longer able to be set up. It was working well up to today. Now the integration is failing completely with the same error above. It logs me out of the browser admin page as expected when I try to refresh or setup the integration again from scratch, but it just `Failed to set up: Check the logs` with the same error. Not working anymore.... Using Archer AXE95.
