### ISSUE TITLE
Archer C60 Cannot authorize! Error

### ISSUE THREAD

**Issue by karl1809** [AlexandrErohin/home-assistant-tplink-router#58]
The Update worked for a short time but now:

TplinkRouter - C1200 - Cannot authorize! Error - 'NoneType' object has no attribute 'get'; Response - {"errorcode":"user conflict","success":false}

Is there any solution of this problem?

**Comment by karl1809** [comment]
I loadet the integration new, and now it works again. Is it a good idea to make in future no updates. Never touch a running system?

**Comment by AlexandrErohin** [comment]
It always requires updates as HA changes and it needs to update for compatibility
