### ISSUE TITLE
Archer AX53 V2 - not working

### ISSUE THREAD

**Issue by iter8tor** [AlexandrErohin/home-assistant-tplink-router#59]
Tested the latest version with my AX53 V2 and latest HA.
It installs correctly, but has a few issues:

- doesn't show the correct clients number (had about 30 on all networks, and the component only showed 12)
- no upload/download speeds
- while being logged in to the AX53, it logged me out every time HA connected to the router to get its data (this was the most annoying issue)

**Comment by AlexandrErohin** [comment]
@iter8tor Hi
So the integrations works with Archer AX53 V2

- no upload/download speeds
The integration doesnt show router speeds. To get this information you may use UPnP HomeAssistant Integration that enables you to collect network statistics from your router such as bytes in/out and packets in/out, uptime, WAN IP address, and WAN connectivity status.
https://www.home-assistant.io/integrations/upnp/

- while being logged in to the AX53, it logged me out every time HA connected to the router to get its data (this was the most annoying issue)
The TP-Link Web Interface only supports upto 1 user logged in at a time (for security reasons, apparently). So you will be logged out from router web interface when the integration updates data

- doesn't show the correct clients number (had about 30 on all networks, and the component only showed 12)
Could you download this client https://github.com/AlexandrErohin/TP-Link-Archer-C6U, run this code and post the result please?
```
from tplinkrouterc6u import TplinkRouter
from logging import Logger

router = TplinkRouter('192.168.0.1', 'password', logger=Logger('test'))
router.authorize()
print(router.request('admin/status?form=all&operation=read'))
```

**Comment by iter8tor** [comment]
It throws the following error:
```
print(router.request('admin/status?form=all&operation=read'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TplinkRequest.request() missing 1 required positional argument: 'data'
```

**Comment by iter8tor** [comment]
For obvious reasons I won't post the output here, but it only lists 12 clients and I have 23.

**Comment by AlexandrErohin** [comment]
@iter8tor You may mask sensitive information like mac address, ip and ect, but I need the output to debug the client

**Comment by iter8tor** [comment]
`{'guest_2g5g_psk_key': '*EDITED*', 'guest_5g_authentication_timeout': '', 'wan_ipv4_netmask': '255.255.255.255', 'wireless_2g_wds_status': 'disable', 'wireless_2g_wep_format2': 'hex', 'wireless_2g_mu_mimo': 'off', 'guest_5g_redirect': 'off', 'wan_ipv6_conntype': 'none', 'wireless_5g_wep_key2': '', 'iot_2g_psk_version': 'rsn', 'iot_2g_encryption': 'psk', 'storage_vendor': '', 'iot_5g_hidden': 'on', 'wireless_2g_wep_type2': '64', 'wireless_5g_wep_select': '1', 'wireless_2g_psk_key': '*EDITED*', 'wireless_2g_wep_type1': '64', 'wireless_5g_wep_type4': '64', 'wan_ipv4_snddns': '*EDITED*', 'wireless_5g_extinfo': {'support_band': 'both', 'wds_guest_compatible': 'no', 'support_guest_dynpasswd': 'no'}, 'guest_2g_hidden': 'on', 'wireless_2g_channel': 'auto', 'wireless_2g_wpa_version': 'auto', 'wireless_5g_psk_key': '*EDITED*', 'guest_5g_redirect_url': '', 'wireless_5g_wep_format2': 'hex', 'iot_2g_ssid': '*EDITED*', 'wireless_5g_wep_key1': '', 'lan_macaddr': '*EDITED*', 'wireless_2g_encryption': 'psk', 'wireless_2g_psk_cipher': 'aes', 'wireless_5g_port': '1812', 'iot_5g_encryption': 'psk', 'wireless_5g_wpa_cipher': 'auto', 'guest_5g_disabled': 'off', 'wireless_5g_wep_type1': '64', 'wireless_5g_disabled_by': '', 'lan_ipv6_link_local_addr': '*EDITED*', 'guest_5g_portal_password': '', 'wan_ipv6_snddns': '::', 'wan_ipv6_pridns': '::', 'wireless_2g_hidden': 'off', 'wireless_5g_wpa_key': '', 'guest_isolate': 'off', 'wan_macaddr': '*EDITED*', 'wireless_5g_hidden': 'on', 'wireless_2g_wep_key4': '', 'wireless_2g_disabled_all': 'off', 'wireless_5g_htmode': '160', 'wireless_2g_wep_key2': '', 'guest_2g_psk_key': '*EDITED*', 'guest_5g_psk_version': 'sae_transition', 'wireless_5g_server': '', 'modem_connstatus': '0', 'wireless_5g_channel': 'auto', 'wan_ipv6_enable': 'off', 'guest_2g5g_psk_version': 'sae_transition', 'wireless_2g_wep_mode': 'auto', 'wireless_5g_wpa_version': 'auto', 'wireless_5g_wep_type3': '64', 'wireless_5g_wds_status': 'disable', 'wireless_2g_wep_format3': 'hex', 'guest_5g_authentication_type': '', 'wireless_5g_disabled': 'off', 'wireless_5g_wep_mode': 'auto', 'storage_available_unit': 'B', 'guest_2g5g_redirect_url': '', 'wireless_5g_wep_format4': 'hex', 'wireless_5g_wep_type2': '64', 'printer_count': 0, 'wireless_5g_wep_format1': 'hex', 'storage_capacity': 0, 'access_devices_wired': [{'wire_type': 'wired', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.9', 'hostname': '*EDITED*'}, {'wire_type': 'wired', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.51', 'hostname': '*EDITED*'}, {'wire_type': 'wired', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.246', 'hostname': '*EDITED*'}, {'wire_type': 'wired', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.101', 'hostname': '*EDITED*'}, {'wire_type': 'wired', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.239', 'hostname': '*EDITED*'}, {'wire_type': 'wired', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.250', 'hostname': '*EDITED*'}], 'storage_available': 0, 'guest_2g_authentication_type': '', 'lan_ipv6_ipaddr': '*EDITED*', 'guest_2g5g_portal_password': '', 'guest_2g_authentication_timeout': '', 'modem_available': 0, 'wireless_2g_disabled': 'off', 'modem_signal': '0%', 'modem_gateway': '0.0.0.0', 'wireless_5g_encryption': 'psk', 'modem_ipaddr': '0.0.0.0', 'guest_5g_hidden': 'on', 'guest_access': 'off', 'modem_ipv4_uptime': '0', 'modem_pridns': '0.0.0.0', 'guest_2g5g_authentication_type': '', 'wireless_5g_disabled_all': 'off', 'guest_5g_extinfo': {'support_band': 'both', 'wds_guest_compatible': 'no', 'support_guest_dynpasswd': 'no'}, 'wireless_5g_current_channel': '48', 'modem_netmask': '0.0.0.0', 'wireless_2g_wpa_cipher': 'auto', 'conn_type': '0', 'iot_2g_hidden': 'off', 'guest_5g_encryption': 'psk_sae', 'wireless_2g_wep_key3': '', 'modem_snddns': '0.0.0.0', 'cpu_usage': 0.08, 'iot_2g_psk_key': '*EDITED*', 'wireless_2g_wep_select': '1', 'iot_2g_enable': 'on', 'iot_5g_psk_key': '*EDITED*', 'access_devices_wireless_host': [{'wire_type': '2.4G', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.67', 'hostname': '*EDITED*'}, {'wire_type': '5G', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.99', 'hostname': '*EDITED*'}, {'wire_type': '2.4G', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.2', 'hostname': '*EDITED*'}, {'wire_type': '5G', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.151', 'hostname': '*EDITED*'}, {'wire_type': '2.4G', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.238', 'hostname': '*EDITED*'}, {'wire_type': '5G', 'macaddr': '*EDITED*', 'ipaddr': '192.168.0.11', 'hostname': '*EDITED*'}], 'cpu1_usage': 0.08, 'mem_usage': 0.52, 'cpu2_usage': 0.09, 'wireless_wps_active': 'on', 'guest_2g_encryption': 'psk_sae', 'guest_2g5g_psk_cipher': 'aes', 'guest_2g_portal_password': '', 'usb_storages': {}, 'modem_pinlock': '0', 'guest_2g_disabled_by': '', 'wireless_5g_wep_key4': '', 'wireless_2g_ssid': '*EDITED*', 'guest_5g_ssid': '*EDITED*', 'wireless_2g_wep_format4': 'hex', 'wireless_2g_macaddr': '*EDITED*', 'guest_2g_ssid': '*EDITED*', 'wireless_5g_psk_cipher': 'aes', 'iot_5g_disabled_by': '', 'guest_2g5g_passwd_cycle': '', 'lan_ipv4_netmask': '255.255.255.0', 'wireless_2g_airtime_fairness': 'off', 'guest_5g_enable': 'off', 'wireless_2g_wep_format1': 'hex', 'guest_2g_psk_version': 'sae_transition', 'wireless_2g_disabled_by': '', 'guest_5g_disabled_by': '', 'wan_ipv4_uptime': 88500, 'wan_ipv6_gateway': '::', 'printer_name': 'None', 'wireless_2g_txpower': 'high', 'wireless_5g_airtime_fairness': 'off', 'guest_2g_psk_cipher': 'aes', 'wireless_2g_psk_version': 'rsn', 'iot_5g_disabled': 'off', 'wireless_5g_txpower': 'high', 'wireless_2g_current_channel': '2', 'wireless_5g_mu_mimo': 'off', 'guest_2g_redirect': 'off', 'wireless_5g_hwmode': 'anacax_5', 'guest_2g_redirect_url': '', 'wireless_2g_wps_state': 'configured', 'wireless_2g_extinfo': {'support_band': 'both', 'wds_guest_compatible': 'no', 'support_guest_dynpasswd': 'no'}, 'wireless_5g_psk_version': 'rsn', 'guest_5g_psk_key': '*EDITED*', 'wireless_2g_server': '', 'iot_5g_psk_cipher': 'aes', 'wireless_5g_wep_format3': 'hex', 'wan_ipv4_ipaddr': '5.12.53.187', 'guest_2g_extinfo': {'support_band': 'both', 'wds_guest_compatible': 'no', 'support_guest_dynpasswd': 'no'}, 'lan_ipv6_assign_type': 'slaac', 'wireless_2g_port': '1812', 'iot_5g_enable': 'on', 'lan_ipv4_ipaddr': '192.168.0.1', 'wireless_2g_wep_key1': '', 'wireless_2g_wep_type3': '64', 'guest_5g_psk_cipher': 'aes', 'iot_2g_psk_cipher': 'aes', 'wireless_5g_enable': 'on', 'wireless_2g_htmode': 'auto', 'wireless_5g_ssid': '*EDITED*', 'iot_2g_disabled_by': '', 'guest_2g_disabled': 'off', 'guest_2g5g_authentication_timeout': '', 'guest_2g5g_encryption': 'psk_sae', 'wireless_2g_enable': 'on', 'wireless_5g_macaddr': '*EDITED*', 'lan_ipv4_dhcp_enable': 'On', 'wireless_2g_wpa_key': '', 'iot_5g_ssid': '*EDITED*', 'wireless_2g_hwmode': 'bgnax', 'iot_5g_psk_version': 'rsn', 'wireless_5g_wps_state': 'configured', 'wan_ipv4_pridns': '*EDITED*', 'guest_2g_enable': 'on', 'wireless_5g_wep_key3': '', 'guest_2g5g_redirect': 'off', 'wireless_2g_wep_type4': '64', 'wan_ipv6_ip6addr': '::', 'storage_capacity_unit': 'B', 'wan_ipv4_conntype': 'pppoe', 'wan_ipv4_gateway': '*EDITED*', 'iot_2g_disabled': 'off'}
`

**Comment by AlexandrErohin** [comment]
@iter8tor Thank you!
This response says you have only 12 clients.
Could you try this one?
```
from tplinkrouterc6u import TplinkRouter
from logging import Logger

router = TplinkRouter('192.168.0.1', 'password', logger=Logger('test'))
router.authorize()
print(router.request('admin/smart_network?form=game_accelerator', 'operation=loadDevice'))
print('---')
print(router.request('admin/wireless?form=statistics', 'operation=load'))
```

**Comment by AlexandrErohin** [comment]
@iter8tor Any updates?
