### ISSUE TITLE
Add download/upload speed to attributes for clients

### ISSUE THREAD

**Issue by nicholas-l** [AlexandrErohin/home-assistant-tplink-router#60]
The Deco M5's that we have display the download speed and upload speed for each client. Could we add this to the attributes for each client?

**Comment by nicholas-l** [comment]
This looks like we need to add the data to [TP-Link-Archer-C6U](https://github.com/AlexandrErohin/TP-Link-Archer-C6U/tree/main) and then we will need to add the change here.

**Comment by AlexandrErohin** [comment]
@nicholas-l Hi
Thanks for PR to client. I have updated this integration. Please try v1.14.0

P.S. Would be great if you could give a star to these 2 repos :) Thanks
