### ISSUE TITLE
Archer ac1200 - not working 

### ISSUE THREAD

**Issue by KapurkarSidharth** [AlexandrErohin/home-assistant-tplink-router#61]
The error i am getting is :
"Your router is not supported. Please add your router support to https://github.com/AlexandrErohin/TP-Link-Archer-C6U by implementing methods for TplinkC6V4Router class"

**Logs**
Logger: custom_components.tplink_router.config_flow
Source: custom_components/tplink_router/config_flow.py:48
integration: TP-Link Router ([documentation](https://github.com/AlexandrErohin/home-assistant-tplink-router), [issues](https://github.com/AlexandrErohin/home-assistant-tplink-router/issues))
First occurred: 12:02:47 PM (3 occurrences)
Last logged: 12:09:14 PM

TplinkRouter Integration Exception - Your router is not supported. Please add your router support to https://github.com/AlexandrErohin/TP-Link-Archer-C6U by implementing methods for TplinkC6V4Router class

**Comment by KapurkarSidharth** [comment]
![Screenshot 2024-06-11 122406](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/122690839/794b12e2-b053-406c-8c2b-481a9515a72b)

**Comment by AlexandrErohin** [comment]
@KapurkarSidharth Hi
It means your router doesnt support. Would be great if you could add your router support to this integration

**Comment by AlexandrErohin** [comment]
https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/55
