### ISSUE TITLE
Constantly being logged out of admin dashboard

### ISSUE THREAD

**Issue by rohanrichards** [AlexandrErohin/home-assistant-tplink-router#63]
**Describe the bug**
After installing this addon I can no longer actually use my router personally. It seems that it's using the same session as me and I keep getting logged out.

**Logs**
Add also all relevant logs from **Settings->System->Logs**.

**Additional Information (please complete the following information)**
 - Router Hardware Version: AXE16000 Quad-Band Wi-Fi 6E Router
 - Router Firmware Version: unknown (latest)
 - Home Assistant Version: 2024.3.3
 - TP-Link Router Integration Component Version: -

**Comment by pbranly** [comment]
Hi 
As far I understood TP-Link access is limited to only one session
Therefore if you want to access your tplink console, you have to temporarily deactivate the HA tplink integration
Phil

**Comment by rohanrichards** [comment]
Very frustrating. I wonder if I can do this via a button in the HA dashboard

**Comment by NicStatic** [comment]
Spook, the custom integration for Home Assistant that adds features missing from Core, includes service calls to disable and enable an integration.

https://spook.boo/

![image](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/96997776/437039a4-0df5-4fca-ab60-d2facf309323)

**Comment by kividid** [comment]
Just spent a while debugging unexpected log-outs. Easy enough to disable the integration temporarily since I rarely need to access my router admin dashboard, but it would be great to explain this behavior in the integration docs.

Didn't see any contributing guidelines so I created #67 to suggest some docs updates.
