### ISSUE TITLE
Archer BE805 confirmed to work perfectly

### ISSUE THREAD

**Issue by taikun114** [AlexandrErohin/home-assistant-tplink-router#66]
Thank you for the amazing custom integration!
I recently replaced a Wi-Fi router from previously used Archer AX73 to Archer BE805, so I tested this custom integration to see if it works.

# What I tested
### Works perfectly
- CPU used
- Memory used
- Total clients
- Total main wifi clients
- Total guest wifi clients
- Total IoT clients
- Total wired clients
- Device tracker for each device

### Not working
- None!

### Works perfectly
- WIFI 2.4G
- WIFI 5G
- WIFI 6G
- Guest WIFI 2.4G
- Guest WIFI 5G
- Guest WIFI 6G
- IoT WIFI 2.4G
- IoT WIFI 5G
- Reboot

### Not working
- IoT WIFI 6G
(The router does not support this function and the switch is shown as "Unavailable". This is normal behaviour, so no problem!)

### Works perfectly
- tplink_router_new_device
- tplink_router_device_online
- tplink_router_device_offline

### Not working
- None!

# Router information when tested
### Hardware version
Archer BE805 v1.0

### Firmware version
1.0.11 Build 20240318 rel.63271(4A50)

## Other Information
Tested without https (SSL) on the Wi-Fi router.

When the IoT network is switched off or there is not a single client, the sensor "Total IoT clients" is shown as "Unavailable", but I am not sure if this is normal behaviour.
For the guest network, it shows "0" regardless of the state of the guest network switch.

The router has an "MLO Network" switch, and it would be even more helpful if that switch were added to this custom integration! (Please let me know if you need more information)

**Comment by AlexandrErohin** [comment]
Thank you for the info :)
