### ISSUE TITLE
Duplicate Key in configuration.yaml

### ISSUE THREAD

**Issue by roguex5** [AlexandrErohin/home-assistant-tplink-router#69]
In following the instructions to add the automation into configuration.yaml, i get a duplicate key error and all my automations disappear.

![image](https://github.com/user-attachments/assets/e0af8e05-c45e-4d8d-9dda-248a464db903)

**Comment by AlexandrErohin** [comment]
You added automation block twice. You need to add the code to automations.yaml file https://www.home-assistant.io/docs/automation/yaml/
