### ISSUE TITLE
CertVerificationError when initially trying to connect to Archer C7v5

### ISSUE THREAD

**Issue by matbro51** [AlexandrErohin/home-assistant-tplink-router#7]
I am testing with **Archer C7 v5.0** Hardware, Firmware **1.2.1 Build 20220715 rel.19099(4555)**

I get this error on trying to login on initial configuration (ip address of router is correct):

`Cannot connect to host 192.168.1.129:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1006)')]`

**Comment by matbro51** [comment]
I don't think HTTPS can be disabled, I just have this:
![image](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/149270280/d09f9cc1-b7c3-4255-9bd9-f77d60305bad)

I tried changing the port for HTTPS to 5443 but just got the same error with :5443 after the host name, so it looks like it redirects from the original port 80 connection.

**Comment by AlexandrErohin** [comment]
Could you try to disable remote management and try the integration?

**Comment by AlexandrErohin** [comment]
Added https connection support

**Comment by AlexandrErohin** [comment]
Added https connection support

**Comment by AlexandrErohin** [comment]
@matbro51 Archer C7 V5 support was added and [tested] (https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/11)
Please reinstall and check

**Comment by matbro51** [comment]
Sorry for not replying sooner and thanks for adding the support.

I still can't connect but I should mention that I am using the C7 in an unusual way - I have it inside my network. So from the HomeAssitant it would need to work through the WAN port's ('outside'/'internet') IP adress, which is in fact a private address on my main internet router. Don't worry about trying to support my weird setup (I'm surprised it doesn't work as the management GUI I see is the same as when I'm getting a DHCP address from the C7, but I will have to find another way to monitor it.)

**Comment by matbro51** [comment]
I have just tried again and it is now working - you can't log on from 2 places at once and I hadn't logged out on the PC - this is great , thanks!   If I run a VPN server on the C7 I can see in the normal GUI how many people are connected - is this something that your add-on could potentially show?

**Comment by AlexandrErohin** [comment]
There are sensors which show how many clients are connected (wired, wifi, guest wifi)

<img src="https://raw.githubusercontent.com/AlexandrErohin/home-assistant-tplink-router/master/docs/media/sensors.png" width="70%">
