### ISSUE TITLE
Deco X60 error sending command.

### ISSUE THREAD

**Issue by Mcgowan412** [AlexandrErohin/home-assistant-tplink-router#71]
**Describe the bug**
I'm unable to turn off the guest WiFi and also the IoT net work says it is disabled when it's actually tuned on. 

**Logs**
This error originated from a custom integration.

Logger: custom_components.tplink_router
Source: custom_components/tplink_router/coordinator.py:66
integration: TP-Link Router (documentation, issues)
First occurred: 02:00:35 (2 occurrences)
Last logged: 02:00:35

TplinkRouter - TPLinkDecoClient - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/wireless?form=wlan - Response
TplinkRouter - TPLinkDecoClient - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/wireless?form=wlan - Response YC6ngthWp+HU7oDgGowDfKya3hD4qvRg2H76AaVQFXf2bgKADq8fjwscAVakWbZ3FGhCl2yVRJKWNRBSf1wAJZPFtvuCW+093tXaSmWguoRZiSq84hI5baW0JsNAjEVJbVRZPZsrHz+LjkmiZFgejKNkdFdRQdlMt5JM/MAyWZpFUOx89OqpDQ4HxpexxlnoBz276cHINrvxkHckNGiKRchOYuOBtlhNU94mAvUx+9yjUO5ZPVWd22B15k95ljc4ZPgAixo0WKKWX68VUprrq8U23wvooNBdKp3je5vULBUT5kK1yDg7hOpzO7zmtPDzDB2IiN086FyjpK8OLZFo0Lj2Qhyvmw/1oAcfUt9ODiQ=

**Additional Information (please complete the following information)**
 - Router Hardware Version:  V3
 - Router Firmware Version: 1.25
 - Home Assistant Version: 2024.7.3
 - TP-Link Router Integration Component Version: 1.15.2

**Comment by AlferNL** [comment]
With my Deco M9plus router, I have a similar problem when turning the guest WiFi (2G/5G) on or off.

**Logs:**
Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:241
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 21. Juli 2024 um 08:46:21 (18 Vorkommnisse)
Zuletzt protokolliert: 14:11:40

[140008783084512] Unexpected exception
[140008609294384] Unexpected exception
[140008593474752] Unexpected exception
[140008783078608] Unexpected exception
[140008602414688] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tplink_router/switch.py", line 145, in async_turn_on
    await self.entity_description.method(self.coordinator, True)
  File "/config/custom_components/tplink_router/coordinator.py", line 68, in set_wifi
    await self.hass.async_add_executor_job(TPLinkRouterCoordinator.request, self.router, callback)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 56, in request
    data = callback()
           ^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 66, in callback
    self.router.set_wifi(wifi, enable)
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 510, in set_wifi
    self.request('admin/wireless?form=wlan', json.dumps({'operation': 'write', 'params': params}))
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 110, in request
    raise ClientError(error)
tplinkrouterc6u.exception.ClientError: TplinkRouter - TPLinkDecoClient - An unknown response - Expecting value: line 1 column 1 (char 0); Request admin/wireless?form=wlan - Response S4em/u8eRD4Qi3X9HIMDzObdOs5ihHjwkI5HXI1b+WCC6iVxEq65S9gL6thneaPA10Qp+mMQXUs6MZWD8ZXG5AlPTluVKQGr33mG69AuWfttVBA+tVLj+Nu5ztbfl7YpAPwZbyF+KmomKcwx6yDeUGVDbkwFE3aOU5+XhgOnG6Fr5jYgQBxdz+21c36nfmXID5pyYT7iAvNM6mRCqIKM5hddobAln1H+PF9C0qrhuT7Rlfy/Oefv3lboOqSe5eg7xfkCBN2Mpx4wzHgWJbtjDLJI/cmWFcL+NCQSqnvxJZA3jOfcfd+sC2/VNujdsFqSinhw8xIvSFZYFfnu4detrGVPXNvp294k0cUOlTKkrZI=

**Additional Information (please complete the following information)**

- Router Hardware Version: M9Plus(1.0)
- Router Firmware Version: 1.6.3 Build 20231225 Rel. 52251
- Home Assistant Version: 2024.7.3
- TP-Link Router Integration Component Version: 1.15.2

**Comment by MDV85** [comment]
Same...

**Comment by ArBohe** [comment]
same...

**Comment by AlexandrErohin** [comment]
As I dont have Deco router - could you use this client https://github.com/AlexandrErohin/TP-Link-Archer-C6U) and play with wifi switch?

There is also issue about Can't turn on/off Guest Wifi on Deco https://github.com/AlexandrErohin/home-assistant-tplink-router/issues/73
Ill close this - so lets go to that issue
