### ISSUE TITLE
• Message malformed: must contain at least one of below, above.

### ISSUE THREAD

**Issue by matt1862000** [AlexandrErohin/home-assistant-tplink-router#72]
I’m new to HA but surely this doesn’t need a value above or below? I can’t move to the next screen. 
![8b0b12f4-7e05-4e94-ab7b-de097f17d9d0](https://github.com/user-attachments/assets/4462c126-f661-4b89-8363-cc714e1efe93)

**Comment by AlexandrErohin** [comment]
You need to use https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger
