### ISSUE TITLE
Archer Ax12 password error

### ISSUE THREAD

**Issue by legolas0802** [AlexandrErohin/home-assistant-tplink-router#75]
**Describe the bug**
Archer ax12 router integration worked for 2 days, now it seems to have problems with login password

**Logs**
Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.tplink_router
Fonte: /usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py:204
Integrazione: TP-Link Router (documentazione, problemi)
Prima occorrenza: 06:58:00 (1 occorrenze)
Ultima registrazione: 06:58:00

TplinkRouter - TPLinkDecoClient - Unknown error for pwd! Error - 'result'; Response - {"success":true,"data":{"password":["D1E79FF135D14E342D76185C23024E6DEAD4D6EC2C317A526C811E83538EA4E5ED8E1B0EEE5CE26E3C1B6A5F1FE11FA804F28B7E8821CA90AFA5B2F300DF99FDA27C9D2131E031EA11463C47944C05005EF4C1CE932D7F4A87C7563581D9F27F0C305023FCE94997EC7D790696E784357ED803A610EBB71B12A8BE5936429BFD","010001"],"mode":"router","username":""}}

Registratore: homeassistant.config_entries
Fonte: config_entries.py:604
Prima occorrenza: 06:58:03 (1 occorrenze)
Ultima registrazione: 06:58:03

Error setting up entry http://192.168.178.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 47, in async_setup_entry
    firmware, status = await hass.async_add_executor_job(TPLinkRouterCoordinator.request, client, callback)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 56, in request
    data = callback()
           ^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 43, in callback
    stat = client.get_status()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 364, in get_status
    _add_device(type, item)
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 355, in _add_device
    ipaddress.IPv4Address(item['ipaddr']),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ipaddress.py", line 1319, in __init__
    self._ip = self._ip_int_from_string(addr_str)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ipaddress.py", line 1206, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'Unknown'

**Additional Information (please complete the following information)**
 - Router Hardware Version: Archer AX12 v1.0
 - Router Firmware Version: 1.1.22 Build 20240311 Rel. 73956
 - Home Assistant Version:  last
 - TP-Link Router Integration Component Version: last

**Comment by AlexandrErohin** [comment]
Hi! This error is ok. As there are different router's API the integrations try to connect to router by different ways. And when it gets fail it write a log.
