### ISSUE TITLE
Integration throws you out of interface for Archer c7

### ISSUE THREAD

**Issue by philmulley** [AlexandrErohin/home-assistant-tplink-router#78]
**Describe the bug**
When the integration is active the Archer C7 router logs me out after around 30 seconds.  When I disable the integration I can remain logged into the web interface of the router.  

**Logs**
Add also all relevant logs from **Settings->System->Logs**. I could not find anything relevant here

**Additional Information (please complete the following information)**
 - Router Hardware Version: V5.0
 - Router Firmware Version: 1.21 (latest)
 - Home Assistant Version: 2024.9.1
 - TP-Link Router Integration Component Version: 1.15.2

**Comment by philmulley** [comment]
I've been blaming my router for this for ages,  but a chance finding on a forum post lead me to test this and there is no issue when the integration is disabled.  The theory is that the integration makes the router "think" that someone is logged on so it throws you out if you are logged into the router's web interface.

**Comment by AlexandrErohin** [comment]
Yes, most TP-Link routers allow only one admin access at a time.
P.S. Dont forget please to give a star to the repo :)

**Comment by philmulley** [comment]
Thanks Alexandr

I've done so.

Phil Mulley
