### ISSUE TITLE
object NoneType can't be used in 'await' expression when submitting IP and password

### ISSUE THREAD

**Issue by alainsmedts** [AlexandrErohin/home-assistant-tplink-router#8]
Archer C6 v2.0
Firmware: 1.3.7 Build 20220613 rel.64828(4555)

Error:
object NoneType can't be used in 'await' expression 
when submitting IP and password

**Comment by AlexandrErohin** [comment]
Try to reinstall it

**Comment by alainsmedts** [comment]
OK, it seems when I installed with HACS, it installed a very old version. I updated to the latest version and rebooted HA.
Now I have following in the logs (note that IP is http://192.168.1.228):
This error originated from a custom integration.

Logger: custom_components.tplink_router
Source: /usr/local/lib/python3.11/site-packages/tplinkrouterc6u/client.py:249
Integration: TP-Link Router (documentation, issues)
First occurred: 16:21:41 (7 occurrences)
Last logged: 16:33:20

'model'
HTTPConnectionPool(host='192.168.0.1', port=80): Max retries exceeded with url: /cgi-bin/luci/;stok=/login?form=keys&operation=read (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xffff5081dc50>, 'Connection to 192.168.0.1 timed out. (connect timeout=4)'))

and
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 16:21:41 (7 occurrences)
Last logged: 16:33:20

Error setting up entry http://192.168.1.228 for tplink_router
Error setting up entry http://192.168.0.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 40, in async_setup_entry
    coord = TPLinkRouterCoordinator(hass, device, config_entry.data[CONF_SCAN_INTERVAL], info, _LOGGER)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 19, in __init__
    self.firmware = info[0]
                    ~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by AlexandrErohin** [comment]
I have added more logs for errors.
@alainsmedts  Could you reinstall it and check the logs again?

**Comment by alainsmedts** [comment]
Updated to latest version and rebooted HA, these are the 2 errors now:
This error originated from a custom integration.

Logger: custom_components.tplink_router
Source: /usr/local/lib/python3.11/site-packages/tplinkrouterc6u/client.py:243
Integration: TP-Link Router (documentation, issues)
First occurred: 17:36:59 (3 occurrences)
Last logged: 17:41:26

TplinkRouter Integration Exception - 'model'

and

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 17:37:02 (3 occurrences)
Last logged: 17:41:26

Error setting up entry http://192.168.1.228 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 40, in async_setup_entry
    coord = TPLinkRouterCoordinator(hass, device, config_entry.data[CONF_SCAN_INTERVAL], info, _LOGGER)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 19, in __init__
    self.firmware = info[0]
                    ~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by AlexandrErohin** [comment]
Good, I needed this log
```
TplinkRouter Integration Exception - 'model'
```
@alainsmedts I have made an update - Could you reinstall it and try again?

**Comment by alainsmedts** [comment]
@AlexandrErohin 
Same issue after update to latest version:
This error originated from a custom integration.

Logger: custom_components.tplink_router
Source: /usr/local/lib/python3.11/site-packages/tplinkrouterc6u/client.py:243
Integration: TP-Link Router (documentation, issues)
First occurred: 20:16:15 (3 occurrences)
Last logged: 20:23:12

TplinkRouter Integration Exception - 'model'

**Comment by AlexandrErohin** [comment]
@alainsmedts Sorry, I have made wrong version tag. There was not included the fix
now the current is v1.2.2. Could you try it?

**Comment by alainsmedts** [comment]
@AlexandrErohin making progress, but another error now:
This error originated from a custom integration.

Logger: custom_components.tplink_router
Source: /usr/local/lib/python3.11/site-packages/tplinkrouterc6u/client.py:243
Integration: TP-Link Router (documentation, issues)
First occurred: 20:55:49 (2 occurrences)
Last logged: 20:59:20

TplinkRouter Integration Exception - 'mem_usage'

**Comment by AlexandrErohin** [comment]
@alainsmedts I have fixed it. Please try v1.2.3

**Comment by alainsmedts** [comment]
@AlexandrErohin 
Works fine now. Many thanks for the quick fixes! 
![image](https://github.com/AlexandrErohin/home-assistant-tplink-router/assets/97637995/7f5e398e-df02-427a-8bd1-f8fe16faaf5d)

**Comment by alainsmedts** [comment]
Thanks for your quick responses, works fine now
