### ISSUE TITLE
Add support to send text messages

### ISSUE THREAD

**Issue by Momro** [AlexandrErohin/home-assistant-tplink-router#85]
Hi,

I have a TL-MR100 v2.0. I use a SIM card and the LTE connection of the router as fallback internet.
I would like to utilize the SIM card for short text messages, too, but I cannot find an integration that does that.

I was able to connect and send a text message like this:

```
python
[...]
from tplinkrouterc6u import (
...     TplinkRouterProvider,
...     TplinkRouter,
...     TplinkC1200Router,
...     TPLinkMRClient,
...     TPLinkDecoClient,
...     Connection
... )

router = TplinkRouterProvider.get_client('http://192.168.9.1', 'xxxxx')
router.authorize()
router.send_sms("017987665432", "hallo aus der python console")
router.logout()
```

This uses https://pypi.org/project/tplinkrouterc6u/#status though, and I was told that you cannot add Python libraries in HAOS, so I'm a bit stuck here.

Any chance you could add this to your integration?

**Comment by Momro** [comment]
It appears to be not exactly possible to do this in python code because one cannot sideload pip libraries though

**Comment by Pel1can111** [comment]
@Momro If you find a solution to achieve this please can you update this. Would be awesome to utilise the sms feature of these routers to send updates/notifications to family/friends that interact with home assistant though physical buttons without setting them up with remote access to HA.

Would also be a great way to fire off critical alerts.

**Comment by iursevla** [comment]
@Momro  Seems like it is possible with [PyScript](https://github.com/custom-components/pyscript)

**Comment by Momro** [comment]
> @Momro @Pel1can111 Seems like it is possible with [PyScript](https://github.com/custom-components/pyscript)
> 
> I also need this feature (sending SMS) and I'm using Typescript code to do it outside of Home Assistant. Basically, event happens in HA -> HA sends MQTT message to topic -> Typescript code is listening to topic -> sends SMS message

But I cannot import said library in HA / I cannot download it. One would maybe have to download the files from pypi manually, upload to HA and import it there... But maybe it would still not be possible depending on the local interpreter of HA

**Comment by iursevla** [comment]
@Momro I saw this video: https://www.youtube.com/watch?v=Kr1rAJnVBrI

**Comment by Momro** [comment]
> @Momro I saw this video: https://www.youtube.com/watch?v=Kr1rAJnVBrI (at 09:05 for script with imports)

Interesting! Relevant part is at 9:45.

Thanks mate!

**Comment by iursevla** [comment]
@Momro any news? Did you try it?

**Comment by AlexandrErohin** [comment]
Added service for sending SMS message in version 2.2.0. Please try and let me know

P.S. Would be great if you could give a star to the repo :) Thanks

**Comment by Pel1can111** [comment]
Thank you! Tested and works perfect, added a star as well!

**Comment by AlexandrErohin** [comment]
@Pel1can111 What is your router hardware version?

**Comment by Pel1can111** [comment]
Firmware: 1.2.0 0.9.1 v0001.0 Build 240718 Rel.53010n
Hardware: Archer MR200 v6.0 00000001

Hope that helps

**Comment by Momro** [comment]
> Added service for sending SMS message in version 2.2.0. Please try and let me know https://github.com/AlexandrErohin/home-assistant-tplink-router?tab=readme-ov-file#send-sms-only-for-mr-lte-routers P.S. Would be great if you could give a star to the repo :) Thanks

I found out that your example in the readme is incorrect. This is how it has to look like:

```
action: tplink_router.send_sms
data:
  number: "+1234567890"
  text: Hello World
  device: 5afce1e27272cb7d997cbe4220891a2d
```

I did't know where to get the device ID from. Maybe others will find it helpful if you mentioned that you can get the ID from the URL when you visit the device page :-)

**Comment by Momro** [comment]
Anyway, thank you so much! Great work, truly helpful!

**Comment by Pel1can111** [comment]
Curious question (I really don't want to come accross as ungrateful for adding this functionality) but firstly would it be very hard to add the last SMS recieved as a sensor? One for the senders number and another for the message?

Mostly curious if this would even be possible and would it useful or crazy?! Seems like an intersting idea to have the ability to trigger an automation by SMS but not sure if its just my mind running a bit too far with this!!

**Comment by Momro** [comment]
Interesting idea, but best to open a new issue because it is a separate topic 😉

**Comment by Pel1can111** [comment]
Looks like the latest update to HA has broken this feature for me, can anyone else confirm?
