### ISSUE TITLE
Printer is listed under the TPlink devices

### ISSUE THREAD

**Issue by ra-kal** [AlexandrErohin/home-assistant-tplink-router#86]
**Describe the bug**
I installed the integration and configured my TPLink router. However, under the TPLink integration, there are now listed two devices: the TPLink router but also my Samsung Printer. The printer is handled by Samsung SyncThru integration. 

 - Home Assistant Version: 2024.10.1
 - TP-Link Router Integration Component Version: 1.15.2

**Comment by AlexandrErohin** [comment]
Hi
What is your router hardware version?

**Comment by ra-kal** [comment]
I figured out that it is due to the device_tracker entity, that the TP Link integration created for the printer. This tracker entity probably cuases the cross-reference between the printer device and the TPlink integration based on MAC address. The entity is listed on the printer device page as well.

**Comment by AlexandrErohin** [comment]
So it is correct work. HA shows connected devices
