### ISSUE TITLE
Not working with C1200 v1 ?

### ISSUE THREAD

**Issue by vingerha** [AlexandrErohin/home-assistant-tplink-router#90]
It refuses to connect to my old router, not sure if this is a known thing. Tried normal pwd and web-encrypted

Error: 
```
TplinkRouter - C1200 - Cannot authorize! Error - 'set-cookie'; Response - {"errorcode":"user conflict","success":false,"data":{}}
```

**Comment by AlexandrErohin** [comment]
Hi
Try to logout from router in every place you login to the router and try again this integration

**Comment by vingerha** [comment]
That did it, I had a uPnP connected ...thx

**Comment by AlexandrErohin** [comment]
@vingerha What is your router hardware version?

**Comment by vingerha** [comment]
OLD :)
Firmware: 1.1.3 Build 20180124 rel.52299 (EU)
Hardware: Archer C1200 v1.0

**Comment by AlexandrErohin** [comment]
And you used web-encrypted pwd for the integration?

**Comment by vingerha** [comment]
yes

**Comment by AlexandrErohin** [comment]
@vingerha Thank you! A will add your hardware version to supported list.
P.S. Dont forget please to give a star to the repo :)
