### ISSUE TITLE
Archer C6 - Unknown error for pwd!

### ISSUE THREAD

**Issue by julll190** [AlexandrErohin/home-assistant-tplink-router#92]
Hi,
I have an Archer C6 v2.0, firmware version 1.3.7 Build 20220613 rel.64828 (it is the latest version).
I enabled the option "access for all LAN connected devices" to be sure that it allow HA to connect.

When the HACS integration tries to login to the router, it fails showing "configuration failed". In the log file I can see the following:
`2024-10-08 15:54:45.941 ERROR (SyncWorker_2) [custom_components.tplink_router] TplinkRouter - TPLinkDecoClient - Unknown error for pwd! Error - 'result'; Response - {"success":true,"data":{"password":["D1FxxxD95","010001"],"mode":"router","username":""}}
2024-10-08 15:54:49.032 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.0.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 47, in async_setup_entry
    firmware, status = await hass.async_add_executor_job(TPLinkRouterCoordinator.request, client, callback)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 56, in request
    data = callback()
           ^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 43, in callback
    stat = client.get_status()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 367, in get_status
    _add_device(type, item)
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 358, in _add_device
    IPv4Address(item['ipaddr']),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ipaddress.py", line 1319, in __init__
    self._ip = self._ip_int_from_string(addr_str)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ipaddress.py", line 1206, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'Unknown'`

When I try to log again into the Archer C6 interface I get a message "Login conflict. Only one device can log in at a time. Do you want to continue and force the other device to log off?", as if the HACS integration is already connected to the router.
If I log into the C6 administration through Chrome, and then reload the HACS integration, I get killed from the C6 administration page.

I tried to restart the router, the HA box, uninstall and reinstall the integration, same problem.
What is surprising is that I am pretty sure that a few days ago the integration successfully connected to the router and showed me the devices connected to the router. But I had no time to investigate when this happened.

**Additional Information (please complete the following information)**
 - Router Hardware Version: Archer C6 v2.0
 - Router Firmware Version: 1.3.7 Build 20220613 rel.64828
 - Home Assistant Version:  Core 2024.9.3, Supervisor 2024.10.0
 - TP-Link Router Integration Component Version: 1.16.0

Thanks a lot!

**Comment by julll190** [comment]
Here is the result.
I replaced some SSID, hostnames, mac address... the values I replaced were good and real values.

`{'wan_ipv4_netmask': '255.255.255.0', 'wireless_2g_wds_status': 'disable', 'wireless_2g_wep_format2': 'hex', 'wireless_5g_txbf_enable': 'on', 'wan_ipv6_conntype': 'none', 'wireless_5g_wep_key2': '', 'wireless_2g_port': '1812', 'wireless_2g_htmode': 'auto', 'storage_vendor': '', 'wireless_2g_wep_type2': '64', 'wireless_5g_wep_select': '1', 'wireless_2g_psk_key': 'PASSWORD', 'wireless_2g_wep_type1': '64', 'wireless_2g_wep_key1': '', 'wan_ipv4_snddns': '192.168.1.254', 'wireless_5g_extinfo': {'support_band': 'both', 'dual_band': 'yes', 'wds2g_wds5g_compatible': 'no'}, 'guest_2g_hidden': 'off', 'wireless_2g_channel': 'auto', 'wireless_2g_wpa_version': 'auto', 'wireless_5g_psk_key': 'PASSWORD', 'lan_ipv4_netmask': '255.255.255.0', 'wireless_5g_wep_key1': '', 'lan_macaddr': 'XX-XX-XX-XX-XX-XX', 'wireless_2g_encryption': 'psk', 'wireless_2g_psk_cipher': 'aes', 'wireless_5g_port': '1812', 'wireless_5g_wps_state': 'configured', 'wireless_5g_wpa_cipher': 'auto', 'guest_5g_disabled': 'off', 'wireless_5g_hwmode': 'anac_5', 'lan_ipv6_link_local_addr': '', 'modem_ipaddr': '0.0.0.0', 'wan_ipv6_snddns': '::', 'wireless_2g_atf': 'off', 'wan_ipv6_ip6addr': '::', 'guest_2g_ssid': 'TP-Link_Guest_SSID', 'wireless_5g_wpa_key': '', 'guest_isolate': 'off', 'wan_macaddr': 'XX-XX-XX-XX-XX-XX', 'wireless_5g_hidden': 'off', 'wireless_2g_wep_key4': '', 'wireless_5g_atf': 'off', 'wireless_2g_disabled_all': 'off', 'wireless_5g_htmode': 'auto', 'wan_ipv4_gateway': '192.168.1.254', 'guest_2g_psk_key': '', 'guest_5g_psk_version': 'rsn', 'wireless_5g_wep_format4': 'hex', 'modem_connstatus': 0, 'wireless_5g_channel': 'auto', 'wan_ipv6_enable': 'off', 'wireless_2g_wep_mode': 'auto', 'wireless_5g_wpa_version': 'auto', 'wireless_5g_wep_type3': '64', 'wireless_5g_wds_status': 'disable', 'wireless_2g_wep_format3': 'hex', 'wireless_5g_disabled': 'off','wireless_5g_wep_type2': '64', 'wireless_5g_wep_format1': 'hex', 'storage_capacity': 0, 'access_devices_wired': [{'wire_type': 'wired', 'macaddr': 'XX-XX-XX-XX-XX-XX', 'ipaddr': '192.168.0.117', 'hostname': 'HOSTNAME'}, {'wire_type': 'wired', 'macaddr': 'XX-XX-XX-XX-XX-XX', 'ipaddr': '192.168.0.XXX', 'hostname': 'HOSTNAME'}, {'wire_type': 'wired', 'macaddr': 'XX-XX-XX-XX-XX-XX', 'ipaddr': '192.168.0.220', 'hostname': 'HOSTNAME'}], 'guest_2g_disabled': 'off', 'guest_5g_psk_key': '', 'remote': False, 'wireless_5g_encryption': 'psk', 'guest_5g_hidden': 'off', 'guest_access': 'off', 'wireless_5g_disabled_all': 'off', 'guest_5g_extinfo': {'support_band': 'both', 'dual_band': 'yes', 'wds2g_wds5g_compatible': 'no'}, 'wireless_5g_current_channel': '40', 'wireless_2g_wpa_cipher': 'auto', 'wireless_2g_txpower': 'high', 'wireless_2g_wep_key3': '', 'wireless_2g_wep_select': '1', 'guest_2g_encryption': 'none', 'wireless_2g_extinfo': {'support_band': 'both', 'dual_band': 'yes', 'wds2g_wds5g_compatible': 'no'}, 'guest_5g_ssid': 'TP-Link_Guest_XXXX_5G', 'wireless_2g_wep_format4': 'hex', 'wireless_2g_macaddr': 'XX-XX-XX-XX-XX-XX', 'guest_5g_enable': 'off', 'guest_2g_psk_version': 'rsn', 'storage_available_unit': 'B', 'wireless_2g_wep_key2': '', 'wan_ipv6_gateway': '::', 'printer_name': 'None', 'usb_available': 0, 'storage_available': 0, 'wireless_2g_wep_format1': 'hex', 'printer_count': 0, 'modem_signal': '0%', 'modem_snddns': '0.0.0.0', 'wireless_2g_current_channel': '4', 'wireless_2g_psk_version': 'rsn','modem_gateway': '0.0.0.0', 'wireless_5g_ssid': 'MYSSID', 'wireless_5g_wep_type1': '64', 'wireless_2g_wps_state': 'configured', 'modem_pridns': '0.0.0.0', 'wireless_5g_psk_version': 'rsn', 'modem_netmask': '0.0.0.0', 'wireless_2g_server': '', 'conn_type': '0', 'modem_available': 0, 'wan_ipv4_ipaddr': '192.168.1.188', 'guest_2g_extinfo': {'support_band': 'both', 'dual_band': 'yes', 'wds2g_wds5g_compatible': 'no'}, 'lan_ipv6_assign_type': 'slaac', 'access_devices_wireless_host': [{'wire_type': '5G', 'macaddr': 'XX-XX-XX-XX-XX-XX', 'ipaddr': '192.168.0.142', 'hostname': 'HOSTNAME'}, {'wire_type': '2.4G', 'macaddr': 'XX-XX-XX-XX-XX-XX', 'ipaddr': 'Unknown', 'hostname': 'Unknown'}, {'wire_type': '2.4G', 'macaddr': 'XX-XX-XX-XX-XX-XX', 'ipaddr': 'Unknown', 'hostname': 'Unknown'}, {'wire_type': '2.4G', 'macaddr': 'XX-XX-XX-XX-XX-XX', 'ipaddr': 'Unknown', 'hostname': 'Unknown'}, {'wire_type': '2.4G', 'macaddr': 'XX-XX-XX-XX-XX-XX', 'ipaddr': '192.168.0.138', 'hostname': 'HOSTNAME'}, {'wire_type': '2.4G', 'macaddr': 'XX-XX-XX-XX-XX-XX', 'ipaddr': '192.168.0.135', 'hostname': 'HOSTNAME'}], 'wireless_2g_wep_type3': '64', 'lan_ipv4_ipaddr': '192.168.0.1', 'wireless_2g_enable': 'on', 'wireless_5g_txpower': 'high', 'guest_5g_psk_cipher': 'aes', 'wireless_2g_disabled': 'off', 'wireless_5g_enable': 'on', 'wireless_5g_wep_type4': '64', 'wireless_5g_mumimo': 'off', 'wireless_2g_wpa_key': '', 'wireless_5g_wep_key4': '', 'guest_5g_encryption': 'none', 'wireless_5g_wep_mode': 'auto', 'wireless_5g_wep_format2': 'hex', 'wireless_5g_macaddr': 'XX-XX-XX-XX-XX-XX', 'lan_ipv4_dhcp_enable': 'On', 'wireless_5g_wep_format3': 'hex', 'wireless_2g_wep_type4': '64', 'wireless_2g_hwmode': 'bgn', 'wireless_5g_server': '', 'wireless_2g_ssid': 'MYSSID', 'wan_ipv4_pridns': 'XX.XX.XX.XX', 'guest_2g_enable': 'off', 'wireless_5g_wep_key3': '', 'wireless_5g_psk_cipher': 'aes', 'wan_ipv6_pridns': '::', 'wireless_2g_hidden': 'off', 'storage_capacity_unit': 'B', 'wan_ipv4_conntype': 'dhcp', 'lan_ipv6_ipaddr': '::/0', 'guest_2g_psk_cipher': 'aes'}`

**Comment by julll190** [comment]
I think I understand what happens.
Your integration connect perfectly to my router, because it logs me off from my Chrome connection (and when I log into the router with Chrome it say that someone is already connected).
Then the integration scans the list of "things" connected to my router, and when it see the name UNKNOWN and the IP address UNKNOWN it cause an error. 
![IMG_20241008_235810](https://github.com/user-attachments/assets/52e1cff2-c6ce-46e1-9885-53e045697fdf)

**Comment by AlexandrErohin** [comment]
@julll190 I have fixed it. Please try version v1.17.0 and let me know

**Comment by julll190** [comment]
Thanks a lot, it works like a charm!
I just need to understand what are these "Unknown" devices in my house :D

**Comment by AlexandrErohin** [comment]
@julll190 Would be great if you could give a star to the repo :) Thanks
