### ISSUE TITLE
Invalid escape sequence in tplinkrouterc6u/client.py

### ISSUE THREAD

**Issue by Paul1865** [AlexandrErohin/home-assistant-tplink-router#96]
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/tplink_router/coordinator.py:6
integration: TP-Link Router (documentation, issues)
First occurred: 21:48:06 (2 occurrences)
Last logged: 21:48:06

/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py:1128: SyntaxWarning: invalid escape sequence '\[' regexp = search('\[\d,\d,\d,\d,\d,\d\](\d)', line)
/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py:1318: SyntaxWarning: invalid escape sequence '\$' result = search('\$\.ret=(.*);', response_text)

**Additional Information (please complete the following information)**
Router:
- Firmware versie: 1.3.4 Build 20230906 rel.74809(4555)
- Hardware versie: Archer AX11000 v1.0

**Comment by AlexandrErohin** [comment]
@pHiR0 Fixed. Please try version 1.19.0
