### ISSUE TITLE
Unable to add TP Link Integration (AX3000 Router)

### ISSUE THREAD

**Issue by Joka69** [AlexandrErohin/home-assistant-tplink-router#97]
**Describe the bug**
Unable to add integration on Home Assistant for my TP LInk Router

**Logs**
From Logs:
This error originated from a custom integration.

Logger: custom_components.tplink_router.config_flow
Source: custom_components/tplink_router/config_flow.py:48
integration: tplink_router (documentation, issues)
First occurred: 5:10:41 PM (12 occurrences)
Last logged: 5:34:39 PM

TplinkRouter Integration Exception -
TplinkRouter Integration Exception - HTTPConnectionPool(host='192.168.0.1', port=80): Read timed out.
TplinkRouter Integration Exception - HTTPSConnectionPool(host='tplinkwifi.net', port=443): Max retries exceeded with url: /cgi/getParm?_=1728486851901 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
TplinkRouter Integration Exception - HTTPConnectionPool(host='tplinkwifi.net', port=80): Read timed out.

**Additional Information (please complete the following information)**
 - Router Hardware Version: AX3000 Dual Band WiFi 6 Router
 - Router Firmware Version: 0.4.0 3.0.0 v607e.0 Build 231108 Rel.5398n
 - Home Assistant Version:  Home Assistant Core 2024.10.1
 - TP-Link Router Integration Component Version: V1.17.0

**Comment by AlexandrErohin** [comment]
@Joka69 You need to use your router local IP - like 192.168.0.1

**Comment by Joka69** [comment]
> @Joka69 You need to use your router local IP - like 192.168.0.1

Hey AlexandrE, I am using my routers local ip, that's the 1 giving me the error added a screenshot of my router logged in using the local IP 
![Screenshot_20241009_201746_Edge](https://github.com/user-attachments/assets/6940643a-a6a1-4c53-8044-340867d77f21)

**Comment by AlexandrErohin** [comment]
https://raw.githubusercontent.com/AlexandrErohin/home-assistant-tplink-router/master/docs/media/config_flow.png
unset Verify ssl
